import { Recipe, RecipeCategory } from './types';

export const recipes: Recipe[] = [
  {
    id: 'hamburger',
    name: 'המבורגר ביתי',
    category: 'meat',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    homeCost: 12,
    deliveryCost: 65,
    emoji: '🍔',
    image: '',
    ingredients: [
      { name: 'בשר טחון', amount: '150 גרם', cost: 6 },
      { name: 'לחמנייה', amount: '1', cost: 2 },
      { name: 'עגבנייה', amount: '½', cost: 1 },
      { name: 'חסה', amount: 'עלים', cost: 1 },
      { name: 'בצל', amount: 'פרוסה', cost: 0.5 },
      { name: 'גבינה צהובה', amount: 'פרוסה', cost: 1.5 },
    ],
    steps: [
      'מוציאים את הבשר מהמקרר 15 דקות לפני הבישול',
      'מגלגלים כדור בשר ולוחצים לקציצה שטוחה',
      'מתבלים במלח ופלפל משני הצדדים',
      'מחממים מחבת על אש גבוהה',
      'מניחים את הקציצה ולא נוגעים! 3 דקות',
      'הופכים ומניחים גבינה מעל',
      'עוד 3 דקות עד שהגבינה נמסה',
      'מרכיבים על הלחמנייה עם הירקות',
      'בתיאבון! 🎉',
    ],
  },
  {
    id: 'pasta-tomato',
    name: 'פסטה ברוטב עגבניות',
    category: 'beginner',
    difficulty: 1,
    prepTime: 5,
    cookTime: 20,
    homeCost: 8,
    deliveryCost: 55,
    emoji: '🍝',
    image: '',
    ingredients: [
      { name: 'פסטה', amount: '100 גרם', cost: 2 },
      { name: 'רסק עגבניות', amount: '½ קופסה', cost: 3 },
      { name: 'שום', amount: '2 שיניים', cost: 0.5 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'בזיליקום', amount: 'קמצוץ', cost: 0.5 },
      { name: 'פרמזן', amount: 'כף', cost: 1 },
    ],
    steps: [
      'מחממים סיר גדול עם מים ומוסיפים מלח',
      'כשהמים רותחים, מוסיפים את הפסטה',
      'מבשלים לפי ההוראות על האריזה',
      'במחבת נפרדת - מחממים שמן זית',
      'מוסיפים שום קצוץ ומטגנים דקה',
      'מוסיפים רסק עגבניות ובזיליקום',
      'מבשלים 5 דקות על אש נמוכה',
      'מסננים את הפסטה ומוסיפים לרוטב',
      'מפזרים פרמזן ומגישים! 🍝',
    ],
  },
  {
    id: 'shakshuka',
    name: 'שקשוקה',
    category: 'cheap',
    difficulty: 2,
    prepTime: 5,
    cookTime: 15,
    homeCost: 10,
    deliveryCost: 45,
    emoji: '🍳',
    image: '',
    ingredients: [
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'עגבניות מרוסקות', amount: 'קופסה', cost: 4 },
      { name: 'בצל', amount: '½', cost: 0.5 },
      { name: 'פלפל', amount: '½', cost: 1 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
      { name: 'כמון', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'מחממים שמן במחבת עמוקה',
      'מטגנים בצל חתוך עד שמזהיב',
      'מוסיפים פלפל חתוך וממשיכים 3 דקות',
      'מוסיפים עגבניות, פפריקה וכמון',
      'מבשלים 5 דקות עד שמתעבה קצת',
      'עושים גומות ברוטב',
      'שוברים ביצה לכל גומה',
      'מכסים ומבשלים 5 דקות',
      'מגישים עם לחם! 🥖',
    ],
  },
  {
    id: 'omelette',
    name: 'חביתה עשירה',
    category: 'fast',
    difficulty: 1,
    prepTime: 3,
    cookTime: 5,
    homeCost: 6,
    deliveryCost: 35,
    emoji: '🥚',
    image: '',
    ingredients: [
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'גבינה צהובה', amount: 'פרוסות', cost: 2 },
      { name: 'חלב', amount: 'כף', cost: 0.3 },
      { name: 'מלח ופלפל', amount: 'קמצוץ', cost: 0.2 },
    ],
    steps: [
      'טורפים ביצים עם חלב, מלח ופלפל',
      'מחממים מחבת עם חמאה או שמן',
      'שופכים את התערובת למחבת',
      'כשמתחיל להיקפא - מוסיפים גבינה',
      'מקפלים לחצי ומגישים! 🍳',
    ],
  },
  {
    id: 'rice-chicken',
    name: 'עוף ואורז',
    category: 'meat',
    difficulty: 2,
    prepTime: 10,
    cookTime: 30,
    homeCost: 18,
    deliveryCost: 70,
    emoji: '🍗',
    image: '',
    ingredients: [
      { name: 'חזה עוף', amount: '200 גרם', cost: 10 },
      { name: 'אורז', amount: 'כוס', cost: 2 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
      { name: 'שום', amount: 'שן', cost: 0.5 },
      { name: 'לימון', amount: '½', cost: 1 },
    ],
    steps: [
      'מבשלים אורז לפי ההוראות',
      'חותכים עוף לרצועות',
      'מתבלים בפפריקה, מלח ופלפל',
      'מחממים שמן במחבת',
      'מטגנים עוף 5-6 דקות מכל צד',
      'מוסיפים שום ומטגנים דקה',
      'סוחטים לימון מעל',
      'מגישים על האורז! 🍚',
    ],
  },
  {
    id: 'toast-cheese',
    name: 'טוסט גבינה מושלם',
    category: 'fast',
    difficulty: 1,
    prepTime: 2,
    cookTime: 5,
    homeCost: 5,
    deliveryCost: 28,
    emoji: '🧀',
    image: '',
    ingredients: [
      { name: 'לחם', amount: '2 פרוסות', cost: 1.5 },
      { name: 'גבינה צהובה', amount: 'פרוסות', cost: 2.5 },
      { name: 'חמאה', amount: 'כף', cost: 1 },
    ],
    steps: [
      'מורחים חמאה על הלחם מבחוץ',
      'מניחים גבינה בין הפרוסות',
      'מחממים מחבת על אש בינונית',
      'מטגנים עד שהלחם מוזהב',
      'הופכים ומטגנים מהצד השני',
      'מגישים חם! 🧀',
    ],
  },
  {
    id: 'tortilla',
    name: 'טורטייה ביתית',
    category: 'easy',
    difficulty: 2,
    prepTime: 10,
    cookTime: 10,
    homeCost: 14,
    deliveryCost: 52,
    emoji: '🌮',
    image: '',
    ingredients: [
      { name: 'טורטייה', amount: '2', cost: 3 },
      { name: 'עוף שניצל', amount: '150 גרם', cost: 7 },
      { name: 'חסה', amount: 'עלים', cost: 1 },
      { name: 'עגבנייה', amount: '1', cost: 1 },
      { name: 'רוטב טחינה', amount: 'כף', cost: 1 },
      { name: 'מלפפון חמוץ', amount: '2', cost: 1 },
    ],
    steps: [
      'מטגנים שניצל עוף במחבת עד שמוזהב',
      'חותכים את השניצל לרצועות',
      'חותכים ירקות לרצועות דקות',
      'מחממים טורטייה במחבת יבשה',
      'מניחים עוף במרכז הטורטייה',
      'מוסיפים ירקות ורוטב',
      'מגלגלים ומגישים! 🌮',
    ],
  },
  {
    id: 'fried-rice',
    name: 'אורז מוקפץ',
    category: 'cheap',
    difficulty: 2,
    prepTime: 5,
    cookTime: 15,
    homeCost: 9,
    deliveryCost: 48,
    emoji: '🍚',
    image: '',
    ingredients: [
      { name: 'אורז מבושל', amount: '2 כוסות', cost: 3 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'בצל ירוק', amount: '2', cost: 1 },
      { name: 'שמן שומשום', amount: 'כפית', cost: 1 },
      { name: 'סויה', amount: 'כף', cost: 1 },
      { name: 'ירקות קפואים', amount: 'חופן', cost: 1 },
    ],
    steps: [
      'מחממים מחבת או ווק על אש גבוהה',
      'מוסיפים שמן ומקפיצים ירקות 2 דק׳',
      'דוחפים לצד ומטגנים ביצים מקושקשות',
      'מוסיפים אורז קר ומערבבים',
      'מוסיפים סויה ושמן שומשום',
      'מקפיצים 3 דקות על אש גבוהה',
      'מפזרים בצל ירוק ומגישים! 🥢',
    ],
  },
  {
    id: 'protein-salad',
    name: 'סלט חלבון',
    category: 'protein',
    difficulty: 1,
    prepTime: 10,
    cookTime: 0,
    homeCost: 15,
    deliveryCost: 58,
    emoji: '🥗',
    image: '',
    ingredients: [
      { name: 'חזה עוף מבושל', amount: '150 גרם', cost: 8 },
      { name: 'עלי חסה', amount: 'קערה', cost: 2 },
      { name: 'עגבניות שרי', amount: '10', cost: 2 },
      { name: 'ביצה קשה', amount: '1', cost: 1 },
      { name: 'גבינה בולגרית', amount: '50 גרם', cost: 2 },
    ],
    steps: [
      'קורעים עלי חסה לקערה',
      'חותכים עגבניות שרי לחצי',
      'חותכים עוף לקוביות',
      'מפוררים גבינה בולגרית',
      'חותכים ביצה קשה לרבעים',
      'מערבבים הכל יחד',
      'מוסיפים רוטב לבחירה! 🥗',
    ],
  },
  {
    id: 'pan-pizza',
    name: 'פיצה במחבת',
    category: 'beginner',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    homeCost: 11,
    deliveryCost: 55,
    emoji: '🍕',
    image: '',
    ingredients: [
      { name: 'בצק פיצה', amount: 'חבילה', cost: 4 },
      { name: 'רוטב עגבניות', amount: '3 כפות', cost: 2 },
      { name: 'מוצרלה', amount: '100 גרם', cost: 4 },
      { name: 'זיתים', amount: 'קומץ', cost: 0.5 },
      { name: 'אורגנו', amount: 'קמצוץ', cost: 0.5 },
    ],
    steps: [
      'מורחים בצק על מחבת משומנת',
      'מחממים על אש בינונית',
      'מורחים רוטב עגבניות',
      'מפזרים גבינה מוצרלה',
      'מוסיפים זיתים ואורגנו',
      'מכסים ומבשלים 10 דקות',
      'הגבינה נמסה? מוכן! 🍕',
    ],
  },
  {
    id: 'toast-avocado',
    name: 'טוסט אבוקדו',
    category: 'fast',
    difficulty: 1,
    prepTime: 5,
    cookTime: 3,
    homeCost: 8,
    deliveryCost: 42,
    emoji: '🥑',
    image: '',
    ingredients: [
      { name: 'לחם מחמצת', amount: '2 פרוסות', cost: 3 },
      { name: 'אבוקדו בשל', amount: '½', cost: 3 },
      { name: 'לימון', amount: 'סחיטה', cost: 0.5 },
      { name: 'מלח ופלפל', amount: 'קמצוץ', cost: 0.2 },
      { name: 'שומשום', amount: 'קמצוץ', cost: 0.3 },
    ],
    steps: [
      'קולים לחם בטוסטר',
      'מועכים אבוקדו במזלג',
      'מוסיפים לימון, מלח ופלפל',
      'מורחים על הלחם הקלוי',
      'מפזרים שומשום',
      'מגישים מיד! 🥑',
    ],
  },
  {
    id: 'noodles',
    name: 'נודלס פשוט',
    category: 'fast',
    difficulty: 1,
    prepTime: 3,
    cookTime: 10,
    homeCost: 7,
    deliveryCost: 38,
    emoji: '🍜',
    image: '',
    ingredients: [
      { name: 'נודלס אטריות', amount: 'חבילה', cost: 3 },
      { name: 'ירקות מוקפצים', amount: 'כוס', cost: 2 },
      { name: 'סויה', amount: 'כף', cost: 0.5 },
      { name: 'שמן שומשום', amount: 'כפית', cost: 0.5 },
      { name: 'שום', amount: 'שן', cost: 0.5 },
      { name: 'בצל ירוק', amount: '1', cost: 0.5 },
    ],
    steps: [
      'מבשלים נודלס לפי ההוראות',
      'מחממים ווק עם שמן',
      'מוסיפים שום ומטגנים 30 שניות',
      'מוסיפים ירקות ומקפיצים 2 דק׳',
      'מוסיפים נודלס מסונן',
      'מוסיפים סויה ושמן שומשום',
      'מפזרים בצל ירוק ומגישים! 🍜',
    ],
  },
  {
    id: 'vegetable-stir-fry',
    name: 'ירקות מוקפצים',
    category: 'vegetarian',
    difficulty: 1,
    prepTime: 10,
    cookTime: 8,
    homeCost: 12,
    deliveryCost: 45,
    emoji: '🥦',
    image: '',
    ingredients: [
      { name: 'ברוקולי', amount: 'ראש קטן', cost: 4 },
      { name: 'גזר', amount: '1', cost: 1 },
      { name: 'פלפל צבעוני', amount: '1', cost: 2 },
      { name: 'פטריות', amount: '100 גרם', cost: 3 },
      { name: 'סויה', amount: 'כף', cost: 1 },
      { name: 'שום', amount: '2 שיניים', cost: 1 },
    ],
    steps: [
      'חותכים ירקות לחתיכות קטנות',
      'מחממים ווק על אש גבוהה',
      'מוסיפים שמן ושום',
      'מוסיפים ירקות קשים קודם (גזר)',
      'אחרי 2 דק׳ מוסיפים שאר הירקות',
      'מקפיצים 4-5 דקות',
      'מוסיפים סויה ומגישים! 🥦',
    ],
  },
  {
    id: 'hummus-plate',
    name: 'צלחת חומוס',
    category: 'vegetarian',
    difficulty: 1,
    prepTime: 5,
    cookTime: 0,
    homeCost: 10,
    deliveryCost: 38,
    emoji: '🧆',
    image: '',
    ingredients: [
      { name: 'חומוס מוכן', amount: 'קופסה', cost: 5 },
      { name: 'טחינה', amount: 'כף', cost: 2 },
      { name: 'פטרוזיליה', amount: 'קומץ', cost: 1 },
      { name: 'פפריקה', amount: 'קמצוץ', cost: 0.5 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'פיתה', amount: '1', cost: 0.5 },
    ],
    steps: [
      'שופכים חומוס לצלחת',
      'יוצרים גומה במרכז',
      'מוסיפים טחינה לגומה',
      'מפזרים פפריקה ופטרוזיליה',
      'שופכים שמן זית מעל',
      'מגישים עם פיתה חמה! 🧆',
    ],
  },
  {
    id: 'falafel',
    name: 'פלאפל ביתי',
    category: 'vegetarian',
    difficulty: 3,
    prepTime: 20,
    cookTime: 15,
    homeCost: 12,
    deliveryCost: 42,
    emoji: '🧆',
    image: '',
    ingredients: [
      { name: 'חומוס יבש (מושרה)', amount: '200 גרם', cost: 3 },
      { name: 'בצל', amount: '1', cost: 1 },
      { name: 'שום', amount: '3 שיניים', cost: 1 },
      { name: 'פטרוזיליה', amount: 'חופן', cost: 1 },
      { name: 'כוסברה', amount: 'חופן', cost: 1 },
      { name: 'כמון', amount: 'כפית', cost: 0.5 },
      { name: 'שמן לטיגון', amount: 'כוס', cost: 3 },
      { name: 'פיתה', amount: '2', cost: 1.5 },
    ],
    steps: [
      'טוחנים חומוס מושרה עם בצל ושום',
      'מוסיפים עשבי תיבול וכמון',
      'מערבבים היטב ומקררים 30 דקות',
      'מחממים שמן עמוק במחבת',
      'יוצרים כדורים קטנים',
      'מטגנים עד שמוזהבים',
      'מגישים בפיתה עם טחינה וסלט! 🧆',
    ],
  },
  {
    id: 'sabich',
    name: 'סביח',
    category: 'vegetarian',
    difficulty: 2,
    prepTime: 15,
    cookTime: 20,
    homeCost: 14,
    deliveryCost: 48,
    emoji: '🍆',
    image: '',
    ingredients: [
      { name: 'חציל', amount: '1 גדול', cost: 3 },
      { name: 'ביצה קשה', amount: '2', cost: 2 },
      { name: 'חומוס', amount: '3 כפות', cost: 2 },
      { name: 'טחינה', amount: '2 כפות', cost: 2 },
      { name: 'סלט ישראלי', amount: 'כוס', cost: 2 },
      { name: 'פיתה', amount: '2', cost: 1.5 },
      { name: 'אמבה', amount: 'כפית', cost: 1.5 },
    ],
    steps: [
      'חותכים חציל לפרוסות עבות',
      'מטגנים חציל בשמן עמוק עד שמוזהב',
      'מבשלים ביצים קשות 10 דקות',
      'פותחים פיתה ומורחים חומוס',
      'מוסיפים חציל מטוגן',
      'מוסיפים ביצים פרוסות וסלט',
      'שופכים טחינה ואמבה מעל! 🍆',
    ],
  },
  {
    id: 'majadara',
    name: 'מג\'דרה',
    category: 'cheap',
    difficulty: 2,
    prepTime: 10,
    cookTime: 40,
    homeCost: 8,
    deliveryCost: 35,
    emoji: '🍚',
    image: '',
    ingredients: [
      { name: 'אורז', amount: 'כוס', cost: 2 },
      { name: 'עדשים ירוקות', amount: 'כוס', cost: 3 },
      { name: 'בצל', amount: '3 גדולים', cost: 2 },
      { name: 'שמן', amount: '3 כפות', cost: 1 },
    ],
    steps: [
      'שוטפים עדשים ומבשלים 20 דקות',
      'חותכים בצל לטבעות דקות',
      'מטגנים בצל בשמן עד חום כהה',
      'מוסיפים אורז לעדשים',
      'מוסיפים מים ומבשלים 20 דקות',
      'מגישים עם בצל מטוגן מעל! 🍚',
    ],
  },
  {
    id: 'schnitzel',
    name: 'שניצל ישראלי',
    category: 'meat',
    difficulty: 2,
    prepTime: 15,
    cookTime: 15,
    homeCost: 16,
    deliveryCost: 58,
    emoji: '🍗',
    image: '',
    ingredients: [
      { name: 'חזה עוף', amount: '300 גרם', cost: 10 },
      { name: 'פירורי לחם', amount: 'כוס', cost: 2 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'קמח', amount: '½ כוס', cost: 0.5 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
      { name: 'שמן לטיגון', amount: 'כוס', cost: 1 },
    ],
    steps: [
      'חותכים עוף לפרוסות דקות',
      'דופקים עם פטיש עד שדק',
      'מכינים 3 צלחות: קמח, ביצים, פירורים',
      'טובלים בקמח, ביצה, פירורים',
      'מחממים שמן במחבת',
      'מטגנים 4 דקות מכל צד',
      'מגישים עם לימון! 🍋',
    ],
  },
  {
    id: 'israeli-salad',
    name: 'סלט ישראלי',
    category: 'fast',
    difficulty: 1,
    prepTime: 10,
    cookTime: 0,
    homeCost: 6,
    deliveryCost: 25,
    emoji: '🥗',
    image: '',
    ingredients: [
      { name: 'עגבניות', amount: '3', cost: 2 },
      { name: 'מלפפונים', amount: '3', cost: 2 },
      { name: 'בצל', amount: '½', cost: 0.5 },
      { name: 'לימון', amount: '½', cost: 0.5 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
    ],
    steps: [
      'חותכים עגבניות לקוביות קטנות',
      'חותכים מלפפונים לקוביות',
      'קוצצים בצל דק דק',
      'מערבבים הכל יחד',
      'מתבלים במלח, לימון ושמן זית',
      'מגישים טרי! 🥗',
    ],
  },
  {
    id: 'couscous',
    name: 'קוסקוס מרוקאי',
    category: 'easy',
    difficulty: 2,
    prepTime: 15,
    cookTime: 30,
    homeCost: 15,
    deliveryCost: 55,
    emoji: '🍲',
    image: '',
    ingredients: [
      { name: 'קוסקוס', amount: 'כוס', cost: 3 },
      { name: 'עוף שוקיים', amount: '4', cost: 8 },
      { name: 'גזר', amount: '2', cost: 1 },
      { name: 'קישוא', amount: '1', cost: 1 },
      { name: 'חומוס מבושל', amount: 'כוס', cost: 1.5 },
      { name: 'צימוקים', amount: 'קומץ', cost: 0.5 },
    ],
    steps: [
      'מטגנים עוף עד שמוזהב',
      'מוסיפים ירקות חתוכים גדול',
      'מכסים במים ומבשלים 30 דקות',
      'מכינים קוסקוס לפי ההוראות',
      'מוסיפים חומוס וצימוקים לרוטב',
      'מגישים קוסקוס עם עוף וירקות! 🍲',
    ],
  },
  {
    id: 'shawarma',
    name: 'שווארמה ביתית',
    category: 'meat',
    difficulty: 2,
    prepTime: 15,
    cookTime: 20,
    homeCost: 18,
    deliveryCost: 65,
    emoji: '🥙',
    image: '',
    ingredients: [
      { name: 'חזה עוף', amount: '300 גרם', cost: 10 },
      { name: 'תבלין שווארמה', amount: 'כף', cost: 1 },
      { name: 'פיתה/לאפה', amount: '2', cost: 2 },
      { name: 'חומוס', amount: '3 כפות', cost: 2 },
      { name: 'סלט כרוב', amount: 'כוס', cost: 1.5 },
      { name: 'טחינה', amount: '2 כפות', cost: 1.5 },
    ],
    steps: [
      'חותכים עוף לרצועות דקות',
      'מתבלים בתבלין שווארמה',
      'מטגנים על אש גבוהה 8 דקות',
      'מחממים פיתה או לאפה',
      'מורחים חומוס על הפיתה',
      'מוסיפים עוף, כרוב וטחינה',
      'מגלגלים ומגישים חם! 🥙',
    ],
  },
  {
    id: 'chicken-soup',
    name: 'מרק עוף',
    category: 'meat',
    difficulty: 2,
    prepTime: 15,
    cookTime: 60,
    homeCost: 18,
    deliveryCost: 48,
    emoji: '🍲',
    image: '',
    ingredients: [
      { name: 'עוף (שוקיים/כנפיים)', amount: '500 גרם', cost: 10 },
      { name: 'גזר', amount: '2', cost: 1 },
      { name: 'סלרי', amount: '2 ענפים', cost: 1.5 },
      { name: 'בצל', amount: '1', cost: 0.5 },
      { name: 'שום', amount: '3 שיניים', cost: 0.5 },
      { name: 'אטריות', amount: '100 גרם', cost: 2 },
      { name: 'שמיר', amount: 'קומץ', cost: 1 },
    ],
    steps: [
      'שמים עוף בסיר עם מים קרים',
      'מביאים לרתיחה ומסירים קצף',
      'מוסיפים ירקות חתוכים גדול',
      'מבשלים שעה על אש נמוכה',
      'מוציאים עוף ומפרקים',
      'מוסיפים אטריות לרוטב',
      'מחזירים עוף ומפזרים שמיר! 🍲',
    ],
  },
  {
    id: 'burekas',
    name: 'בורקס גבינה',
    category: 'easy',
    difficulty: 2,
    prepTime: 15,
    cookTime: 25,
    homeCost: 10,
    deliveryCost: 38,
    emoji: '🥧',
    image: '',
    ingredients: [
      { name: 'בצק עלים', amount: 'חבילה', cost: 5 },
      { name: 'גבינה בולגרית', amount: '150 גרם', cost: 3 },
      { name: 'ביצה', amount: '1', cost: 1 },
      { name: 'שומשום', amount: 'כף', cost: 0.5 },
    ],
    steps: [
      'מחממים תנור ל-180°',
      'פורסים בצק עלים',
      'חותכים למלבנים',
      'שמים גבינה מפוררת במרכז',
      'מקפלים ולוחצים קצוות',
      'מורחים ביצה ומפזרים שומשום',
      'אופים 25 דקות עד שמוזהב! 🥧',
    ],
  },
  {
    id: 'malawach',
    name: 'מלאווח',
    category: 'beginner',
    difficulty: 1,
    prepTime: 5,
    cookTime: 10,
    homeCost: 8,
    deliveryCost: 35,
    emoji: '🫓',
    image: '',
    ingredients: [
      { name: 'מלאווח קפוא', amount: '2', cost: 4 },
      { name: 'עגבנייה מגורדת', amount: '1', cost: 1 },
      { name: 'ביצה', amount: '2', cost: 2 },
      { name: 'סחוג', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'מחממים מחבת על אש בינונית',
      'מניחים מלאווח קפוא',
      'מטגנים 4 דקות מכל צד',
      'מגרדים עגבנייה בינתיים',
      'מכינים ביצה רכה לצד',
      'מגישים עם עגבנייה וסחוג! 🫓',
    ],
  },
  {
    id: 'ptitim',
    name: 'פתיתים',
    category: 'cheap',
    difficulty: 1,
    prepTime: 5,
    cookTime: 15,
    homeCost: 7,
    deliveryCost: 32,
    emoji: '🍝',
    image: '',
    ingredients: [
      { name: 'פתיתים', amount: 'כוס', cost: 3 },
      { name: 'בצל', amount: '1', cost: 1 },
      { name: 'שמן', amount: 'כף', cost: 0.5 },
      { name: 'מרק עוף (אבקה)', amount: 'כפית', cost: 0.5 },
      { name: 'כורכום', amount: 'קמצוץ', cost: 0.5 },
    ],
    steps: [
      'מטגנים בצל קצוץ בשמן',
      'מוסיפים פתיתים ומערבבים',
      'מטגנים 2 דקות עד שמוזהב',
      'מוסיפים 2 כוסות מים רותחים',
      'מוסיפים מרק וכורכום',
      'מבשלים 12 דקות עד שנספג! 🍝',
    ],
  },
  {
    id: 'shakshuka-green',
    name: 'שקשוקה ירוקה',
    category: 'vegetarian',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    homeCost: 14,
    deliveryCost: 52,
    emoji: '🥬',
    image: '',
    ingredients: [
      { name: 'תרד/מנגולד', amount: 'צרור', cost: 4 },
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'שום', amount: '3 שיניים', cost: 1 },
      { name: 'גבינת פטה', amount: '50 גרם', cost: 3 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'לימון', amount: '½', cost: 1 },
    ],
    steps: [
      'שוטפים וחותכים עלים ירוקים',
      'מטגנים שום בשמן זית',
      'מוסיפים עלים ומבשלים 5 דקות',
      'עושים גומות ושוברים ביצים',
      'מכסים ומבשלים 5 דקות',
      'מפזרים פטה ולימון ומגישים! 🥬',
    ],
  },
  {
    id: 'matbucha',
    name: 'מטבוחה',
    category: 'cheap',
    difficulty: 2,
    prepTime: 10,
    cookTime: 45,
    homeCost: 8,
    deliveryCost: 28,
    emoji: '🌶️',
    image: '',
    ingredients: [
      { name: 'עגבניות', amount: '6', cost: 4 },
      { name: 'פלפל אדום', amount: '2', cost: 2 },
      { name: 'שום', amount: '4 שיניים', cost: 1 },
      { name: 'שמן', amount: '2 כפות', cost: 0.5 },
      { name: 'פפריקה חריפה', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'צולים פלפלים בתנור עד שמושחרים',
      'מקלפים וחותכים לרצועות',
      'קולפים עגבניות וחותכים',
      'מטגנים שום בשמן',
      'מוסיפים עגבניות ופלפלים',
      'מבשלים 45 דקות על אש נמוכה',
      'מגישים קר עם פיתה! 🌶️',
    ],
  },
  {
    id: 'tehina-salad',
    name: 'סלט טחינה',
    category: 'fast',
    difficulty: 1,
    prepTime: 5,
    cookTime: 0,
    homeCost: 6,
    deliveryCost: 22,
    emoji: '🥣',
    image: '',
    ingredients: [
      { name: 'טחינה גולמית', amount: '½ כוס', cost: 4 },
      { name: 'לימון', amount: '1', cost: 1 },
      { name: 'שום', amount: 'שן', cost: 0.3 },
      { name: 'מים', amount: '½ כוס', cost: 0 },
      { name: 'פטרוזיליה', amount: 'קומץ', cost: 0.7 },
    ],
    steps: [
      'שמים טחינה בקערה',
      'מוסיפים מיץ לימון ושום כתוש',
      'מוסיפים מים בהדרגה ומערבבים',
      'מתבלים במלח',
      'מפזרים פטרוזיליה מעל',
      'מגישים עם פיתה או ירקות! 🥣',
    ],
  },
  // ===== NEW RECIPES =====
  {
    id: 'french-fries',
    name: 'צ׳יפס ביתי',
    category: 'fast',
    difficulty: 2,
    prepTime: 15,
    cookTime: 20,
    homeCost: 8,
    deliveryCost: 28,
    emoji: '🍟',
    image: '',
    ingredients: [
      { name: 'תפוחי אדמה', amount: '4 בינוניים', cost: 4 },
      { name: 'שמן לטיגון עמוק', amount: '2 כוסות', cost: 3 },
      { name: 'מלח', amount: 'לפי הטעם', cost: 0.5 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'קולפים תפו״א וחותכים לרצועות עבות',
      'משרים במים קרים 30 דק׳ (מוציא עמילן)',
      'מייבשים טוב טוב עם מגבת',
      'מחממים שמן ל-180 מעלות',
      'מטגנים במנות קטנות 5-7 דק׳',
      'מוציאים, מתבלים במלח חם',
      'יאללה לטבול בקטשופ! 🍟',
    ],
  },
  {
    id: 'onion-rings',
    name: 'טבעות בצל',
    category: 'fast',
    difficulty: 2,
    prepTime: 15,
    cookTime: 10,
    homeCost: 10,
    deliveryCost: 32,
    emoji: '🧅',
    image: '',
    ingredients: [
      { name: 'בצל גדול', amount: '2', cost: 2 },
      { name: 'קמח', amount: 'כוס', cost: 1 },
      { name: 'ביצה', amount: '1', cost: 1 },
      { name: 'בירה/מים מוגזים', amount: 'כוס', cost: 2 },
      { name: 'פירורי לחם', amount: 'כוס', cost: 2 },
      { name: 'שמן לטיגון', amount: 'כוס', cost: 2 },
    ],
    steps: [
      'חותכים בצל לטבעות עבות',
      'מפרידים לטבעות בודדות',
      'מכינים בלילה: קמח, ביצה, בירה',
      'טובלים טבעת בבלילה, אח״כ בפירורים',
      'מטגנים בשמן חם 2-3 דק׳',
      'מנגבים על נייר סופג',
      'קראנצ׳י בטירוף! 🧅',
    ],
  },
  {
    id: 'sushi',
    name: 'סושי ביתי',
    category: 'protein',
    difficulty: 3,
    prepTime: 30,
    cookTime: 20,
    homeCost: 35,
    deliveryCost: 95,
    emoji: '🍣',
    image: '',
    ingredients: [
      { name: 'אורז סושי', amount: 'כוס', cost: 5 },
      { name: 'חומץ אורז', amount: '2 כפות', cost: 2 },
      { name: 'אצות נורי', amount: '5 יריעות', cost: 8 },
      { name: 'סלמון טרי', amount: '200 גרם', cost: 15 },
      { name: 'מלפפון', amount: '1', cost: 1 },
      { name: 'אבוקדו', amount: '1', cost: 4 },
    ],
    steps: [
      'מבשלים אורז ומערבבים עם חומץ',
      'מצננים את האורז לטמפרטורת החדר',
      'פורשים נורי על מחצלת גלגול',
      'מורחים שכבת אורז דקה',
      'שמים רצועות סלמון, מלפפון ואבוקדו',
      'מגלגלים בעדינות והדק',
      'חותכים לחתיכות וטובלים בסויה! 🍣',
    ],
  },
  {
    id: 'sushi-kosher',
    name: 'סושי כשר',
    category: 'kosher',
    difficulty: 3,
    prepTime: 30,
    cookTime: 20,
    homeCost: 30,
    deliveryCost: 85,
    emoji: '🍣',
    image: '',
    ingredients: [
      { name: 'אורז סושי', amount: 'כוס', cost: 5 },
      { name: 'חומץ אורז', amount: '2 כפות', cost: 2 },
      { name: 'אצות נורי', amount: '5 יריעות', cost: 8 },
      { name: 'סלמון מעושן', amount: '150 גרם', cost: 10 },
      { name: 'מלפפון', amount: '1', cost: 1 },
      { name: 'אבוקדו', amount: '1', cost: 4 },
    ],
    steps: [
      'מבשלים אורז ומערבבים עם חומץ',
      'מצננים לטמפרטורת החדר',
      'פורשים נורי על מחצלת',
      'מורחים אורז בשכבה דקה',
      'מניחים סלמון מעושן, מלפפון ואבוקדו',
      'מגלגלים הדק וחותכים',
      'כשר ומדהים! ✡️🍣',
    ],
  },
  {
    id: 'fried-chicken',
    name: 'עוף קריספי',
    category: 'meat',
    difficulty: 2,
    prepTime: 20,
    cookTime: 20,
    homeCost: 18,
    deliveryCost: 58,
    emoji: '🍗',
    image: '',
    ingredients: [
      { name: 'כרעי עוף', amount: '6', cost: 12 },
      { name: 'חלב/מים', amount: 'כוס', cost: 1 },
      { name: 'קמח', amount: 'כוס', cost: 1 },
      { name: 'פפריקה', amount: '2 כפיות', cost: 1 },
      { name: 'שום אבקה', amount: 'כפית', cost: 0.5 },
      { name: 'שמן לטיגון', amount: '2 כוסות', cost: 2.5 },
    ],
    steps: [
      'משרים עוף בחלב שעה (מרכך)',
      'מערבבים קמח עם כל התבלינים',
      'מנערים עוף ומצפים בתערובת',
      'נותנים לנוח 10 דק׳',
      'מטגנים בשמן חם 8-10 דק׳',
      'הופכים ומטגנים עוד 8 דק׳',
      'קריספי כמו KFC! 🍗',
    ],
  },
  {
    id: 'thai-curry',
    name: 'קארי תאילנדי',
    category: 'protein',
    difficulty: 2,
    prepTime: 15,
    cookTime: 25,
    homeCost: 22,
    deliveryCost: 68,
    emoji: '🍛',
    image: '',
    ingredients: [
      { name: 'חזה עוף', amount: '300 גרם', cost: 10 },
      { name: 'משחת קארי אדום/ירוק', amount: '2 כפות', cost: 4 },
      { name: 'חלב קוקוס', amount: 'פחית', cost: 5 },
      { name: 'ירקות (פלפל, חציל)', amount: 'כוס', cost: 2 },
      { name: 'בזיליקום תאילנדי', amount: 'חופן', cost: 1 },
    ],
    steps: [
      'חותכים עוף לקוביות',
      'מחממים מחבת ומטגנים משחת קארי',
      'מוסיפים עוף ומבשלים 5 דק׳',
      'שופכים חלב קוקוס',
      'מוסיפים ירקות חתוכים',
      'מבשלים 15 דק׳ על אש נמוכה',
      'מפזרים בזיליקום ומגישים עם אורז! 🍛',
    ],
  },
  {
    id: 'pad-thai',
    name: 'פאד תאי',
    category: 'protein',
    difficulty: 3,
    prepTime: 20,
    cookTime: 15,
    homeCost: 20,
    deliveryCost: 65,
    emoji: '🍜',
    image: '',
    ingredients: [
      { name: 'אטריות אורז', amount: '200 גרם', cost: 4 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'טופו/עוף', amount: '150 גרם', cost: 6 },
      { name: 'בוטנים', amount: 'קומץ', cost: 2 },
      { name: 'רוטב פאד תאי', amount: '3 כפות', cost: 4 },
      { name: 'נבטים', amount: 'חופן', cost: 1 },
      { name: 'בצל ירוק', amount: '2', cost: 1 },
    ],
    steps: [
      'משרים אטריות במים חמים 10 דק׳',
      'מחממים ווק על אש גבוהה',
      'מטגנים ביצים ודוחפים לצד',
      'מוסיפים עוף/טופו ומטגנים',
      'מוסיפים אטריות ורוטב',
      'מקפיצים 3 דק׳ עד שנספג',
      'מגישים עם נבטים ובוטנים! 🍜',
    ],
  },
  {
    id: 'ramen',
    name: 'ראמן יפני',
    category: 'beginner',
    difficulty: 2,
    prepTime: 15,
    cookTime: 20,
    homeCost: 18,
    deliveryCost: 58,
    emoji: '🍜',
    image: '',
    ingredients: [
      { name: 'אטריות ראמן', amount: 'חבילה', cost: 4 },
      { name: 'מרק עוף', amount: '4 כוסות', cost: 4 },
      { name: 'רוטב סויה', amount: '2 כפות', cost: 1 },
      { name: 'ביצה רכה', amount: '2', cost: 2 },
      { name: 'בצל ירוק', amount: '2', cost: 1 },
      { name: 'פטריות', amount: '100 גרם', cost: 4 },
      { name: 'שמן שומשום', amount: 'כפית', cost: 2 },
    ],
    steps: [
      'מבשלים מרק עם סויה ושמן שומשום',
      'מבשלים אטריות בנפרד',
      'מבשלים ביצים רכות 6.5 דק׳',
      'מטגנים פטריות חתוכות',
      'שמים אטריות בקערה',
      'שופכים מרק רותח מעל',
      'מוסיפים טופינגס ויאללה! 🍜',
    ],
  },
  {
    id: 'poke-bowl',
    name: 'פוקה בול',
    category: 'protein',
    difficulty: 2,
    prepTime: 20,
    cookTime: 15,
    homeCost: 28,
    deliveryCost: 72,
    emoji: '🥗',
    image: '',
    ingredients: [
      { name: 'סלמון טרי', amount: '200 גרם', cost: 15 },
      { name: 'אורז סושי', amount: 'כוס', cost: 3 },
      { name: 'אבוקדו', amount: '1', cost: 4 },
      { name: 'אדממה', amount: 'חופן', cost: 2 },
      { name: 'מלפפון', amount: '1', cost: 1 },
      { name: 'רוטב פונזו', amount: '2 כפות', cost: 3 },
    ],
    steps: [
      'מבשלים אורז ומצננים',
      'חותכים סלמון לקוביות',
      'מרינדים בסויה ושמן שומשום',
      'חותכים אבוקדו ומלפפון',
      'מסדרים אורז בקערה',
      'מסדרים כל מרכיב בצד',
      'שופכים רוטב ויאללה לאכול! 🥗',
    ],
  },
  {
    id: 'burrito',
    name: 'בוריטו',
    category: 'easy',
    difficulty: 2,
    prepTime: 15,
    cookTime: 15,
    homeCost: 18,
    deliveryCost: 55,
    emoji: '🌯',
    image: '',
    ingredients: [
      { name: 'טורטייה גדולה', amount: '2', cost: 4 },
      { name: 'בשר טחון', amount: '200 גרם', cost: 8 },
      { name: 'אורז', amount: 'כוס מבושל', cost: 1 },
      { name: 'שעועית שחורה', amount: 'חצי פחית', cost: 2 },
      { name: 'גבינה מגורדת', amount: 'חופן', cost: 2 },
      { name: 'סלסה', amount: '2 כפות', cost: 1 },
    ],
    steps: [
      'מטגנים בשר עם תבלין מקסיקני',
      'מחממים שעועית עם כמון',
      'מחממים טורטייה במחבת',
      'מורחים במרכז אורז, בשר, שעועית',
      'מוסיפים גבינה וסלסה',
      'מקפלים צדדים ומגלגלים',
      'אפשר לצלות על מחבת לקראנץ׳! 🌯',
    ],
  },
  {
    id: 'tacos',
    name: 'טאקו',
    category: 'easy',
    difficulty: 2,
    prepTime: 15,
    cookTime: 15,
    homeCost: 16,
    deliveryCost: 52,
    emoji: '🌮',
    image: '',
    ingredients: [
      { name: 'קליפות טאקו', amount: '8', cost: 5 },
      { name: 'בשר טחון', amount: '250 גרם', cost: 8 },
      { name: 'עגבנייה', amount: '1', cost: 1 },
      { name: 'חסה', amount: 'עלים', cost: 0.5 },
      { name: 'גבינה צהובה', amount: 'חופן', cost: 1 },
      { name: 'שמנת חמוצה', amount: '2 כפות', cost: 0.5 },
    ],
    steps: [
      'מטגנים בשר עם תבלין טאקו',
      'חותכים עגבנייה לקוביות קטנות',
      'קורעים חסה לרצועות',
      'מחממים קליפות טאקו בתנור',
      'ממלאים כל קליפה בבשר',
      'מוסיפים ירקות, גבינה ושמנת',
      'טאקו טיים! 🌮',
    ],
  },
  {
    id: 'dim-sum',
    name: 'דים סאם',
    category: 'beginner',
    difficulty: 3,
    prepTime: 30,
    cookTime: 15,
    homeCost: 18,
    deliveryCost: 65,
    emoji: '🥟',
    image: '',
    ingredients: [
      { name: 'עיסת וונטון', amount: 'חבילה', cost: 6 },
      { name: 'בשר טחון/עוף', amount: '200 גרם', cost: 8 },
      { name: 'בצל ירוק', amount: '2', cost: 1 },
      { name: "ג'ינג'ר", amount: 'כפית מגורד', cost: 1 },
      { name: 'סויה', amount: 'כף', cost: 0.5 },
      { name: 'שמן שומשום', amount: 'כפית', cost: 1.5 },
    ],
    steps: [
      'מערבבים בשר עם כל התיבול',
      'שמים כפית מילוי במרכז כל עיסה',
      'מקפלים ולוחצים קצוות',
      'מסדרים בסיר אידוי על נייר',
      'מאדים 10-12 דקות',
      'מגישים עם רוטב סויה ושומשום',
      'כמו במסעדה סינית! 🥟',
    ],
  },
  {
    id: 'fish-chips',
    name: "פיש אנד צ'יפס",
    category: 'protein',
    difficulty: 2,
    prepTime: 20,
    cookTime: 20,
    homeCost: 25,
    deliveryCost: 72,
    emoji: '🐟',
    image: '',
    ingredients: [
      { name: 'פילה דג לבן', amount: '400 גרם', cost: 15 },
      { name: 'קמח', amount: 'כוס', cost: 1 },
      { name: 'בירה קרה', amount: 'כוס', cost: 3 },
      { name: 'תפו״א', amount: '4', cost: 4 },
      { name: 'שמן לטיגון', amount: '3 כוסות', cost: 2 },
    ],
    steps: [
      'חותכים תפו״א לצ׳יפס ומטגנים',
      'מערבבים קמח, בירה, מלח לבלילה',
      'חותכים דג לרצועות',
      'טובלים דג בבלילה',
      'מטגנים 4-5 דק׳ עד שמוזהב',
      'מנגבים ומתבלים',
      'מגישים עם לימון וטרטר! 🐟',
    ],
  },
  {
    id: 'asian-dumplings',
    name: 'כיסוני אסיה',
    category: 'easy',
    difficulty: 2,
    prepTime: 25,
    cookTime: 15,
    homeCost: 16,
    deliveryCost: 55,
    emoji: '🥟',
    image: '',
    ingredients: [
      { name: 'עיסת גיוזה', amount: 'חבילה', cost: 5 },
      { name: 'בשר חזיר/עוף טחון', amount: '200 גרם', cost: 7 },
      { name: 'כרוב', amount: 'כוס קצוץ', cost: 1 },
      { name: 'בצל ירוק', amount: '2', cost: 1 },
      { name: 'סויה', amount: 'כף', cost: 0.5 },
      { name: 'שמן', amount: 'כף', cost: 1.5 },
    ],
    steps: [
      'מערבבים בשר, כרוב קצוץ דק, בצל',
      'מוסיפים סויה ומלח',
      'שמים כפית מילוי בכל עיסה',
      'מקפלים לחצי ולוחצים',
      'מטגנים במחבת 2 דק׳',
      'מוסיפים מים ומכסים 5 דק׳',
      'מגישים עם רוטב טבילה! 🥟',
    ],
  },
  {
    id: 'grilled-chicken',
    name: 'עוף על האש',
    category: 'meat',
    difficulty: 2,
    prepTime: 15,
    cookTime: 25,
    homeCost: 18,
    deliveryCost: 62,
    emoji: '🍗',
    image: '',
    ingredients: [
      { name: 'שוקי עוף/חזה', amount: '500 גרם', cost: 12 },
      { name: 'שמן זית', amount: '2 כפות', cost: 2 },
      { name: 'לימון', amount: '1', cost: 1 },
      { name: 'שום', amount: '4 שיניים', cost: 1 },
      { name: 'פפריקה מעושנת', amount: 'כפית', cost: 1 },
      { name: 'עשבי תיבול', amount: 'כף', cost: 1 },
    ],
    steps: [
      'מערבבים כל התבלינים עם שמן ולימון',
      'מרינדים עוף לפחות שעה',
      'מחממים גריל/מחבת פסים',
      'צולים 6-7 דק׳ מכל צד',
      'נותנים לנוח 5 דק׳',
      'מגישים עם סלטים וצ׳יפס',
      'ריח של קיץ! 🍗',
    ],
  },
  {
    id: 'caesar-salad',
    name: 'סלט קיסר',
    category: 'fast',
    difficulty: 1,
    prepTime: 15,
    cookTime: 10,
    homeCost: 16,
    deliveryCost: 52,
    emoji: '🥗',
    image: '',
    ingredients: [
      { name: 'חסה רומית', amount: 'ראש', cost: 4 },
      { name: 'חזה עוף', amount: '150 גרם', cost: 6 },
      { name: 'קרוטונים', amount: 'חופן', cost: 2 },
      { name: 'פרמזן', amount: '50 גרם', cost: 3 },
      { name: 'רוטב קיסר', amount: '3 כפות', cost: 1 },
    ],
    steps: [
      'צולים/מטגנים חזה עוף מתובל',
      'חותכים לרצועות',
      'קורעים חסה לקערה גדולה',
      'מוסיפים קרוטונים ופרמזן מגורד',
      'מניחים עוף מעל',
      'שופכים רוטב ומערבבים',
      'קלאסיקה! 🥗',
    ],
  },
  {
    id: 'bbq-ribs',
    name: 'צלעות ברביקיו',
    category: 'meat',
    difficulty: 3,
    prepTime: 15,
    cookTime: 120,
    homeCost: 45,
    deliveryCost: 120,
    emoji: '🍖',
    image: '',
    ingredients: [
      { name: 'צלעות בקר/טלה', amount: '1 ק״ג', cost: 35 },
      { name: 'רוטב BBQ', amount: 'כוס', cost: 5 },
      { name: 'סוכר חום', amount: '2 כפות', cost: 1 },
      { name: 'פפריקה מעושנת', amount: '2 כפיות', cost: 1 },
      { name: 'שום אבקה', amount: 'כפית', cost: 1 },
      { name: 'מלח', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'מערבבים תבלינים יבשים',
      'משפשפים על הצלעות',
      'עוטפים בנייר כסף',
      'אופים בתנור 150° שעתיים',
      'מוציאים מהנייר, מורחים BBQ',
      'צולים עוד 15 דק׳ על גריל',
      'נופל מהעצם! 🍖',
    ],
  },
  {
    id: 'steak',
    name: 'סטייק פרפקט',
    category: 'meat',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    homeCost: 55,
    deliveryCost: 140,
    emoji: '🥩',
    image: '',
    ingredients: [
      { name: 'אנטריקוט/סינטה', amount: '300 גרם', cost: 45 },
      { name: 'חמאה', amount: '2 כפות', cost: 3 },
      { name: 'שום', amount: '3 שיניים', cost: 1 },
      { name: 'רוזמרין', amount: 'ענף', cost: 2 },
      { name: 'מלח גס', amount: 'כפית', cost: 0.5 },
      { name: 'פלפל שחור', amount: 'לטעם', cost: 0.5 },
    ],
    steps: [
      'מוציאים סטייק מהמקרר 30 דק׳ לפני',
      'מתבלים במלח ופלפל משני הצדדים',
      'מחממים מחבת חם חם חם',
      'צולים 3-4 דק׳ מכל צד (medium)',
      'מוסיפים חמאה, שום ורוזמרין',
      'מזליפים על הסטייק',
      'נותנים לנוח 5 דק׳ ואוכלים! 🥩',
    ],
  },
  {
    id: 'kebabs',
    name: 'קבב על האש',
    category: 'meat',
    difficulty: 2,
    prepTime: 20,
    cookTime: 15,
    homeCost: 22,
    deliveryCost: 65,
    emoji: '🍢',
    image: '',
    ingredients: [
      { name: 'בשר טחון (בקר/כבש)', amount: '500 גרם', cost: 15 },
      { name: 'בצל', amount: '1 מגורד', cost: 1 },
      { name: 'פטרוזיליה', amount: 'חופן', cost: 1 },
      { name: 'כמון', amount: 'כפית', cost: 0.5 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
      { name: 'שיפודי עץ', amount: '10', cost: 2 },
    ],
    steps: [
      'משרים שיפודים במים',
      'מערבבים בשר עם בצל מגורד',
      'מוסיפים תבלינים ופטרוזיליה',
      'לשים היטב עד שדביק',
      'יוצרים נקניקיות על שיפודים',
      'צולים על גריל 3-4 דק׳ מכל צד',
      'מגישים בפיתה עם טחינה! 🍢',
    ],
  },
  {
    id: 'poutine',
    name: 'פוטין קנדי',
    category: 'easy',
    difficulty: 2,
    prepTime: 15,
    cookTime: 25,
    homeCost: 18,
    deliveryCost: 55,
    emoji: '🍟',
    image: '',
    ingredients: [
      { name: 'תפו״א', amount: '4', cost: 4 },
      { name: 'גבינת צ׳דר/גאודה', amount: '150 גרם', cost: 8 },
      { name: 'רוטב בשר (גרייבי)', amount: 'כוס', cost: 4 },
      { name: 'שמן לטיגון', amount: '2 כוסות', cost: 2 },
    ],
    steps: [
      'חותכים תפו״א לצ׳יפס עבה',
      'מטגנים עד שמוזהבים וקריספיים',
      'מחממים רוטב בשר',
      'שמים צ׳יפס בצלחת',
      'מפזרים קוביות גבינה',
      'שופכים רוטב חם מעל',
      'הגבינה נמסה... אממממ! 🍟',
    ],
  },
  {
    id: 'tandoori-chicken',
    name: 'טנדורי צ׳יקן',
    category: 'meat',
    difficulty: 2,
    prepTime: 30,
    cookTime: 30,
    homeCost: 20,
    deliveryCost: 65,
    emoji: '🍗',
    image: '',
    ingredients: [
      { name: 'שוקי עוף', amount: '6', cost: 12 },
      { name: 'יוגורט', amount: 'כוס', cost: 3 },
      { name: 'תבלין טנדורי', amount: '2 כפות', cost: 2 },
      { name: 'לימון', amount: '1', cost: 1 },
      { name: "ג'ינג'ר", amount: 'כפית', cost: 1 },
      { name: 'שום', amount: '4 שיניים', cost: 1 },
    ],
    steps: [
      'עושים חתכים בעוף',
      'מערבבים יוגורט עם כל התבלינים',
      'מרינדים עוף לפחות 4 שעות',
      'מחממים תנור ל-220°',
      'אופים 25-30 דק׳',
      'צולים עוד 5 דק׳ בגריל לצבע',
      'אדום ומושלם! 🍗',
    ],
  },
  {
    id: 'butter-chicken',
    name: 'באטר צ׳יקן',
    category: 'meat',
    difficulty: 2,
    prepTime: 20,
    cookTime: 30,
    homeCost: 25,
    deliveryCost: 72,
    emoji: '🍛',
    image: '',
    ingredients: [
      { name: 'חזה עוף', amount: '400 גרם', cost: 12 },
      { name: 'עגבניות מרוסקות', amount: 'פחית', cost: 4 },
      { name: 'שמנת מתוקה', amount: 'כוס', cost: 5 },
      { name: 'חמאה', amount: '3 כפות', cost: 2 },
      { name: 'גראם מסאלה', amount: 'כפית', cost: 1 },
      { name: 'כורכום', amount: 'כפית', cost: 1 },
    ],
    steps: [
      'חותכים עוף לקוביות ומתבלים',
      'מטגנים בחמאה עד שמוזהב',
      'מוציאים עוף, מוסיפים עגבניות',
      'מבשלים 15 דק׳',
      'מוסיפים שמנת ותבלינים',
      'מחזירים עוף ומבשלים 10 דק׳',
      'קרמי בטירוף עם אורז! 🍛',
    ],
  },
  {
    id: 'biryani',
    name: 'בירייאני',
    category: 'meat',
    difficulty: 3,
    prepTime: 30,
    cookTime: 45,
    homeCost: 28,
    deliveryCost: 75,
    emoji: '🍛',
    image: '',
    ingredients: [
      { name: 'אורז בסמטי', amount: '2 כוסות', cost: 5 },
      { name: 'עוף/כבש', amount: '400 גרם', cost: 15 },
      { name: 'בצל', amount: '2 גדולים', cost: 2 },
      { name: 'יוגורט', amount: 'חצי כוס', cost: 2 },
      { name: 'תבלין בירייאני', amount: '2 כפות', cost: 2 },
      { name: 'זעפרן/כורכום', amount: 'קמצוץ', cost: 2 },
    ],
    steps: [
      'משרים אורז 30 דק׳',
      'מטגנים בצל עד שמוזהב',
      'מוסיפים בשר ותבלינים',
      'מוסיפים יוגורט ומבשלים 20 דק׳',
      'מבשלים אורז 70%',
      'שכבות: בשר, אורז, בצל מטוגן',
      'אופים מכוסה 20 דק׳! 🍛',
    ],
  },
  {
    id: 'burrata-tomato',
    name: 'בורטה ועגבניות',
    category: 'fast',
    difficulty: 1,
    prepTime: 10,
    cookTime: 0,
    homeCost: 25,
    deliveryCost: 65,
    emoji: '🍅',
    image: '',
    ingredients: [
      { name: 'בורטה', amount: '1 כדור', cost: 15 },
      { name: 'עגבניות שרי', amount: '200 גרם', cost: 4 },
      { name: 'בזיליקום', amount: 'חופן', cost: 2 },
      { name: 'שמן זית', amount: '2 כפות', cost: 2 },
      { name: 'בלסמי', amount: 'כף', cost: 2 },
    ],
    steps: [
      'חותכים עגבניות לחצי',
      'מסדרים בצלחת',
      'שמים בורטה במרכז',
      'קורעים עלי בזיליקום',
      'שופכים שמן זית ובלסמי',
      'מתבלים במלח ופלפל',
      'איטליה בצלחת! 🍅',
    ],
  },
  {
    id: 'buffalo-wings',
    name: 'כנפיים באפלו',
    category: 'meat',
    difficulty: 2,
    prepTime: 15,
    cookTime: 45,
    homeCost: 20,
    deliveryCost: 58,
    emoji: '🍗',
    image: '',
    ingredients: [
      { name: 'כנפי עוף', amount: '1 ק״ג', cost: 12 },
      { name: 'רוטב חריף', amount: 'חצי כוס', cost: 4 },
      { name: 'חמאה', amount: '4 כפות', cost: 3 },
      { name: 'שום אבקה', amount: 'כפית', cost: 0.5 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'מחממים תנור ל-200°',
      'מתבלים כנפיים במלח ותבלינים',
      'אופים 40 דק׳ עד שקריספי',
      'ממיסים חמאה עם רוטב חריף',
      'מערבבים כנפיים ברוטב',
      'אופים עוד 5 דק׳',
      'מגישים עם רוטב כחול! 🍗',
    ],
  },
  {
    id: 'quesadilla',
    name: 'קסדייה',
    category: 'fast',
    difficulty: 1,
    prepTime: 10,
    cookTime: 10,
    homeCost: 14,
    deliveryCost: 45,
    emoji: '🧀',
    image: '',
    ingredients: [
      { name: 'טורטייה גדולה', amount: '2', cost: 4 },
      { name: 'גבינה מגורדת', amount: 'כוס', cost: 5 },
      { name: 'עוף מבושל', amount: '100 גרם', cost: 4 },
      { name: 'פלפל', amount: 'חצי', cost: 0.5 },
      { name: 'בצל', amount: 'רבע', cost: 0.5 },
    ],
    steps: [
      'מטגנים בצל ופלפל',
      'מוסיפים עוף חתוך',
      'שמים טורטייה במחבת',
      'מפזרים גבינה ומילוי',
      'מכסים בטורטייה שנייה',
      'הופכים כשהגבינה נמסה',
      'חותכים למשולשים ואוכלים! 🧀',
    ],
  },
  {
    id: 'greek-gyro',
    name: "ג'יירו יווני",
    category: 'meat',
    difficulty: 2,
    prepTime: 20,
    cookTime: 15,
    homeCost: 18,
    deliveryCost: 58,
    emoji: '🥙',
    image: '',
    ingredients: [
      { name: 'בשר טחון כבש/בקר', amount: '400 גרם', cost: 12 },
      { name: 'פיתה יוונית', amount: '4', cost: 3 },
      { name: 'צזיקי', amount: 'חצי כוס', cost: 2 },
      { name: 'עגבנייה', amount: '1', cost: 0.5 },
      { name: 'בצל', amount: 'חצי', cost: 0.5 },
    ],
    steps: [
      'מערבבים בשר עם תבלינים יווניים',
      'יוצרים כדור ולוחצים שטוח',
      'צולים במחבת 5 דק׳ מכל צד',
      'חותכים לרצועות דקות',
      'מחממים פיתה',
      'ממלאים בשר, ירקות וצזיקי',
      'אופה יווני! 🥙',
    ],
  },
  {
    id: 'brisket',
    name: 'בריסקט',
    category: 'meat',
    difficulty: 3,
    prepTime: 20,
    cookTime: 240,
    homeCost: 65,
    deliveryCost: 150,
    emoji: '🐄',
    image: '',
    ingredients: [
      { name: 'בריסקט', amount: '1.5 ק״ג', cost: 55 },
      { name: 'בצל', amount: '3', cost: 2 },
      { name: 'שום', amount: 'ראש', cost: 2 },
      { name: 'מרק בשר', amount: '2 כוסות', cost: 3 },
      { name: 'פפריקה מעושנת', amount: '2 כפיות', cost: 1 },
      { name: 'סוכר חום', amount: 'כף', cost: 0.5 },
    ],
    steps: [
      'משפשפים בשר בתבלינים',
      'צורבים במחבת מכל הצדדים',
      'שמים בסיר עם בצל ושום',
      'מוסיפים מרק ומכסים',
      'אופים ב-150° ארבע שעות',
      'נותנים לנוח 20 דק׳',
      'חותכים נגד הסיב - נמס בפה! 🐄',
    ],
  },
  {
    id: 'meatballs-mash',
    name: 'קציצות ופירה',
    category: 'meat',
    difficulty: 2,
    prepTime: 20,
    cookTime: 30,
    homeCost: 20,
    deliveryCost: 58,
    emoji: '🍝',
    image: '',
    ingredients: [
      { name: 'בשר טחון', amount: '400 גרם', cost: 10 },
      { name: 'תפו״א', amount: '4', cost: 4 },
      { name: 'ביצה', amount: '1', cost: 1 },
      { name: 'פירורי לחם', amount: 'רבע כוס', cost: 1 },
      { name: 'חמאה', amount: '3 כפות', cost: 2 },
      { name: 'חלב', amount: 'חצי כוס', cost: 1 },
    ],
    steps: [
      'מערבבים בשר, ביצה, פירורים',
      'יוצרים כדורים קטנים',
      'מטגנים או אופים 20 דק׳',
      'מבשלים תפו״א עד רכים',
      'מועכים עם חמאה וחלב',
      'מתבלים במלח ופלפל',
      'קומפורט פוד! 🍝',
    ],
  },
  {
    id: 'pasta-alfredo',
    name: 'פסטה אלפרדו',
    category: 'beginner',
    difficulty: 1,
    prepTime: 5,
    cookTime: 20,
    homeCost: 15,
    deliveryCost: 55,
    emoji: '🍝',
    image: '',
    ingredients: [
      { name: 'פטוצ׳יני', amount: '250 גרם', cost: 4 },
      { name: 'שמנת מתוקה', amount: 'כוס', cost: 5 },
      { name: 'חמאה', amount: '3 כפות', cost: 2 },
      { name: 'פרמזן', amount: 'חצי כוס מגורד', cost: 3 },
      { name: 'שום', amount: '2 שיניים', cost: 1 },
    ],
    steps: [
      'מבשלים פסטה אל דנטה',
      'ממיסים חמאה עם שום',
      'מוסיפים שמנת ומחממים',
      'מוסיפים פרמזן ומערבבים',
      'מסננים פסטה ומוסיפים לרוטב',
      'מערבבים עד שמצופה',
      'קרמי ופשוט! 🍝',
    ],
  },
  {
    id: 'carbonara',
    name: 'קרבונרה',
    category: 'beginner',
    difficulty: 2,
    prepTime: 10,
    cookTime: 20,
    homeCost: 18,
    deliveryCost: 62,
    emoji: '🍝',
    image: '',
    ingredients: [
      { name: 'ספגטי', amount: '250 גרם', cost: 3 },
      { name: 'בייקון/פנצ׳טה', amount: '150 גרם', cost: 8 },
      { name: 'ביצים', amount: '3 חלמונים + 1 שלמה', cost: 3 },
      { name: 'פרמזן', amount: 'חצי כוס', cost: 3 },
      { name: 'פלפל שחור', amount: 'לטעם', cost: 1 },
    ],
    steps: [
      'מבשלים פסטה, שומרים מים!',
      'מטגנים בייקון עד קריספי',
      'טורפים ביצים עם פרמזן',
      'מסננים פסטה ומחזירים לסיר',
      'מוסיפים בייקון (בלי אש!)',
      'מוסיפים תערובת ביצים ומערבבים מהר',
      'המים מהפסטה יוצרים קרם! 🍝',
    ],
  },
  {
    id: 'lasagna',
    name: 'לזניה',
    category: 'easy',
    difficulty: 3,
    prepTime: 30,
    cookTime: 45,
    homeCost: 28,
    deliveryCost: 75,
    emoji: '🍝',
    image: '',
    ingredients: [
      { name: 'יריעות לזניה', amount: 'חבילה', cost: 5 },
      { name: 'בשר טחון', amount: '400 גרם', cost: 10 },
      { name: 'רוטב עגבניות', amount: '2 כוסות', cost: 4 },
      { name: 'רוטב בשמל', amount: '2 כוסות', cost: 5 },
      { name: 'מוצרלה', amount: '200 גרם', cost: 4 },
    ],
    steps: [
      'מטגנים בשר עם רוטב עגבניות',
      'מכינים/קונים בשמל מוכן',
      'שכבות בתבנית: רוטב, יריעות, בשר, בשמל',
      'חוזרים 3 פעמים',
      'מכסים במוצרלה',
      'אופים מכוסה 30 דק׳, גלוי 15 דק׳',
      'נותנים לנוח 10 דק׳ לפני חיתוך! 🍝',
    ],
  },
  {
    id: 'calzone',
    name: 'קלצונה',
    category: 'easy',
    difficulty: 2,
    prepTime: 20,
    cookTime: 20,
    homeCost: 15,
    deliveryCost: 52,
    emoji: '🍕',
    image: '',
    ingredients: [
      { name: 'בצק פיצה', amount: 'כדור', cost: 4 },
      { name: 'מוצרלה', amount: '150 גרם', cost: 4 },
      { name: 'רוטב עגבניות', amount: 'רבע כוס', cost: 2 },
      { name: 'נקניקיות', amount: '100 גרם', cost: 4 },
      { name: 'פטריות', amount: 'חצי כוס', cost: 1 },
    ],
    steps: [
      'מחממים תנור ל-220°',
      'מורדים בצק לעיגול',
      'שמים מילוי בחצי',
      'מקפלים ולוחצים קצוות',
      'עושים חתכים קטנים למעלה',
      'מורחים שמן זית',
      'אופים 18-20 דק׳ עד שמוזהב! 🍕',
    ],
  },
  {
    id: 'steak-sandwich',
    name: 'סנדוויץ׳ סטייק',
    category: 'meat',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    homeCost: 32,
    deliveryCost: 78,
    emoji: '🥪',
    image: '',
    ingredients: [
      { name: 'סטייק דק', amount: '200 גרם', cost: 22 },
      { name: 'באגט/צ׳יאבטה', amount: '1', cost: 4 },
      { name: 'בצל מקורמל', amount: 'חצי כוס', cost: 2 },
      { name: 'גבינה', amount: 'פרוסות', cost: 3 },
      { name: 'רוקט', amount: 'חופן', cost: 1 },
    ],
    steps: [
      'צולים סטייק 2-3 דק׳ מכל צד',
      'נותנים לנוח, חותכים רצועות',
      'מקרמלים בצל (20 דק׳ על אש נמוכה)',
      'חותכים לחם ומחממים',
      'שכבות: רוקט, סטייק, בצל, גבינה',
      'סוגרים ולוחצים קצת',
      'הסנדוויץ׳ הכי טוב! 🥪',
    ],
  },
  {
    id: 'vegan-burger',
    name: 'המבורגר טבעוני',
    category: 'vegetarian',
    difficulty: 2,
    prepTime: 20,
    cookTime: 15,
    homeCost: 15,
    deliveryCost: 55,
    emoji: '🌱',
    image: '',
    ingredients: [
      { name: 'שעועית שחורה', amount: 'פחית', cost: 4 },
      { name: 'פטריות', amount: 'כוס', cost: 3 },
      { name: 'שיבולת שועל', amount: 'חצי כוס', cost: 1 },
      { name: 'בצל', amount: 'חצי', cost: 0.5 },
      { name: 'לחמניית המבורגר', amount: '2', cost: 3 },
      { name: 'אבוקדו', amount: 'חצי', cost: 3.5 },
    ],
    steps: [
      'מרסקים שעועית במזלג',
      'קוצצים פטריות ובצל דק',
      'מערבבים עם שיבולת שועל ותבלינים',
      'יוצרים 2 קציצות',
      'צולים במחבת 4 דק׳ מכל צד',
      'מרכיבים עם אבוקדו וירקות',
      'טבעוני וטעים! 🌱',
    ],
  },
  {
    id: 'pad-see-ew',
    name: 'פאד סי יו',
    category: 'fast',
    difficulty: 2,
    prepTime: 15,
    cookTime: 10,
    homeCost: 16,
    deliveryCost: 52,
    emoji: '🍜',
    image: '',
    ingredients: [
      { name: 'אטריות אורז רחבות', amount: '200 גרם', cost: 4 },
      { name: 'עוף/טופו', amount: '150 גרם', cost: 5 },
      { name: 'ברוקולי סיני', amount: 'כוס', cost: 3 },
      { name: 'ביצה', amount: '1', cost: 1 },
      { name: 'רוטב סויה כהה', amount: '2 כפות', cost: 2 },
      { name: 'שום', amount: '3 שיניים', cost: 1 },
    ],
    steps: [
      'משרים אטריות עד רכות',
      'מחממים ווק על אש גבוהה מאוד',
      'מטגנים שום ועוף 3 דק׳',
      'דוחפים לצד, מטגנים ביצה',
      'מוסיפים אטריות וירקות',
      'שופכים סויה ומקפיצים',
      'צריך להיות קצת שרוף - זה הסוד! 🍜',
    ],
  },
  {
    id: 'sashimi',
    name: 'סשימי',
    category: 'protein',
    difficulty: 2,
    prepTime: 15,
    cookTime: 0,
    homeCost: 45,
    deliveryCost: 110,
    emoji: '🍣',
    image: '',
    ingredients: [
      { name: 'סלמון סשימי', amount: '200 גרם', cost: 25 },
      { name: 'טונה סשימי', amount: '150 גרם', cost: 15 },
      { name: 'סויה', amount: 'לטבילה', cost: 1 },
      { name: 'וואסאבי', amount: 'כפית', cost: 2 },
      { name: "ג'ינג'ר כבוש", amount: 'לצד', cost: 2 },
    ],
    steps: [
      'מקפיאים דג קצת (קל לחתוך)',
      'חותכים בסכין חדה בזווית',
      'פרוסות של חצי ס״מ',
      'מסדרים יפה על צלחת',
      'מגישים עם סויה ווואסאבי',
      'טובלים ואוכלים!',
      'טרי ופשוט מדהים! 🍣',
    ],
  },
  {
    id: 'sashimi-kosher',
    name: 'סשימי כשר',
    category: 'kosher',
    difficulty: 2,
    prepTime: 15,
    cookTime: 0,
    homeCost: 35,
    deliveryCost: 95,
    emoji: '🍣',
    image: '',
    ingredients: [
      { name: 'סלמון טרי', amount: '250 גרם', cost: 20 },
      { name: 'דג לבן (דניס/בס)', amount: '150 גרם', cost: 10 },
      { name: 'סויה', amount: 'לטבילה', cost: 1 },
      { name: 'וואסאבי', amount: 'כפית', cost: 2 },
      { name: "ג'ינג'ר כבוש", amount: 'לצד', cost: 2 },
    ],
    steps: [
      'בודקים שהדג עם קשקשים (כשר)',
      'מקפיאים קצת לחיתוך קל',
      'חותכים פרוסות דקות בזווית',
      'מסדרים יפה על צלחת',
      'מגישים עם סויה ווואסאבי',
      'כשר ואיכותי! ✡️🍣',
    ],
  },
  {
    id: 'crepes',
    name: 'קרפים מתוקים',
    category: 'beginner',
    difficulty: 1,
    prepTime: 10,
    cookTime: 15,
    homeCost: 10,
    deliveryCost: 38,
    emoji: '🥞',
    image: '',
    ingredients: [
      { name: 'קמח', amount: 'כוס', cost: 1 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'חלב', amount: 'כוס', cost: 2 },
      { name: 'סוכר', amount: 'כף', cost: 0.5 },
      { name: 'נוטלה/שוקולד', amount: 'לצד', cost: 4 },
      { name: 'פירות', amount: 'לצד', cost: 0.5 },
    ],
    steps: [
      'מערבבים קמח, ביצים, חלב, סוכר',
      'משאירים 10 דק׳ לנוח',
      'מחממים מחבת דקה עם חמאה',
      'שופכים מעט בלילה ומסובבים',
      'הופכים אחרי דקה',
      'מורחים נוטלה ומוסיפים פירות',
      'מקפלים ונהנים! 🥞',
    ],
  },
  {
    id: 'ice-cream',
    name: 'גלידה ביתית',
    category: 'beginner',
    difficulty: 2,
    prepTime: 20,
    cookTime: 0,
    homeCost: 15,
    deliveryCost: 45,
    emoji: '🍨',
    image: '',
    ingredients: [
      { name: 'שמנת מתוקה', amount: '2 כוסות', cost: 8 },
      { name: 'חלב מרוכז', amount: 'פחית', cost: 5 },
      { name: 'וניל', amount: 'כפית', cost: 1 },
      { name: 'תוספות (שוקולד צ׳יפס)', amount: 'לבחירה', cost: 1 },
    ],
    steps: [
      'מקציפים שמנת עד שקשה',
      'מוסיפים חלב מרוכז ווניל',
      'מקפלים בעדינות',
      'מוסיפים תוספות לבחירה',
      'שופכים לכלי ומקפיאים',
      'לפחות 6 שעות',
      'גלידה קרמית בלי מכונה! 🍨',
    ],
  },
  // ===== CAKES (10) =====
  {
    id: 'chocolate-cake',
    name: 'עוגת שוקולד קלאסית',
    category: 'desserts',
    difficulty: 2,
    prepTime: 20,
    cookTime: 35,
    homeCost: 18,
    deliveryCost: 65,
    emoji: '🎂',
    image: '',
    ingredients: [
      { name: 'קמח', amount: '2 כוסות', cost: 2 },
      { name: 'סוכר', amount: 'כוס', cost: 1 },
      { name: 'קקאו', amount: '½ כוס', cost: 3 },
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'שמן', amount: '½ כוס', cost: 2 },
      { name: 'חלב', amount: 'כוס', cost: 2 },
      { name: 'אבקת אפייה', amount: 'כפית', cost: 0.5 },
      { name: 'שוקולד לציפוי', amount: '100 גרם', cost: 4.5 },
    ],
    steps: [
      'מחממים תנור ל-180°',
      'מערבבים חומרים יבשים',
      'מוסיפים ביצים, שמן וחלב',
      'מערבבים עד לבלילה חלקה',
      'שופכים לתבנית משומנת',
      'אופים 35 דקות',
      'ממיסים שוקולד ומצפים',
      'עוגה מושלמת! 🎂',
    ],
  },
  {
    id: 'cheesecake',
    name: 'עוגת גבינה אפויה',
    category: 'desserts',
    difficulty: 3,
    prepTime: 25,
    cookTime: 60,
    homeCost: 25,
    deliveryCost: 85,
    emoji: '🧀',
    image: '',
    ingredients: [
      { name: 'גבינת שמנת', amount: '500 גרם', cost: 10 },
      { name: 'גבינה לבנה', amount: '250 גרם', cost: 4 },
      { name: 'סוכר', amount: 'כוס', cost: 1 },
      { name: 'ביצים', amount: '4', cost: 4 },
      { name: 'שמנת חמוצה', amount: '200 מ"ל', cost: 4 },
      { name: 'וניל', amount: 'כפית', cost: 1 },
      { name: 'עוגיות לבסיס', amount: 'חבילה', cost: 1 },
    ],
    steps: [
      'טוחנים עוגיות עם חמאה לבסיס',
      'לוחצים בתחתית התבנית',
      'מקציפים גבינות עם סוכר',
      'מוסיפים ביצים אחת אחת',
      'מוסיפים שמנת ווניל',
      'שופכים על הבסיס',
      'אופים ב-160° שעה',
      'מקררים לילה שלם! 🧀',
    ],
  },
  {
    id: 'carrot-cake',
    name: 'עוגת גזר',
    category: 'desserts',
    difficulty: 2,
    prepTime: 25,
    cookTime: 45,
    homeCost: 20,
    deliveryCost: 70,
    emoji: '🥕',
    image: '',
    ingredients: [
      { name: 'גזר מגורר', amount: '3 כוסות', cost: 4 },
      { name: 'קמח', amount: '2 כוסות', cost: 2 },
      { name: 'סוכר חום', amount: 'כוס', cost: 2 },
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'שמן', amount: '¾ כוס', cost: 3 },
      { name: 'קינמון', amount: 'כפית', cost: 1 },
      { name: 'אגוזי מלך', amount: '½ כוס', cost: 4 },
      { name: 'גבינת שמנת לציפוי', amount: '200 גרם', cost: 1 },
    ],
    steps: [
      'מחממים תנור ל-180°',
      'מערבבים ביצים עם סוכר ושמן',
      'מוסיפים קמח וקינמון',
      'מקפלים גזר ואגוזים',
      'שופכים לתבנית',
      'אופים 45 דקות',
      'מצפים בקרם גבינה',
      'מושלמת! 🥕',
    ],
  },
  {
    id: 'apple-cake',
    name: 'עוגת תפוחים',
    category: 'desserts',
    difficulty: 2,
    prepTime: 20,
    cookTime: 50,
    homeCost: 16,
    deliveryCost: 55,
    emoji: '🍎',
    image: '',
    ingredients: [
      { name: 'תפוחים', amount: '4', cost: 5 },
      { name: 'קמח', amount: '2 כוסות', cost: 2 },
      { name: 'סוכר', amount: '¾ כוס', cost: 1 },
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'שמן', amount: '½ כוס', cost: 2 },
      { name: 'קינמון', amount: 'כפית', cost: 1 },
      { name: 'אבקת אפייה', amount: 'כפית', cost: 0.5 },
      { name: 'סוכר חום לפיזור', amount: '2 כפות', cost: 1.5 },
    ],
    steps: [
      'מחממים תנור ל-180°',
      'קולפים וחותכים תפוחים',
      'מערבבים ביצים עם סוכר',
      'מוסיפים שמן, קמח וקינמון',
      'מקפלים תפוחים לבלילה',
      'שופכים לתבנית',
      'מפזרים סוכר חום מעל',
      'אופים 50 דקות! 🍎',
    ],
  },
  {
    id: 'red-velvet',
    name: 'עוגת רד וולווט',
    category: 'desserts',
    difficulty: 3,
    prepTime: 30,
    cookTime: 30,
    homeCost: 28,
    deliveryCost: 95,
    emoji: '❤️',
    image: '',
    ingredients: [
      { name: 'קמח', amount: '2½ כוסות', cost: 2.5 },
      { name: 'קקאו', amount: '2 כפות', cost: 1 },
      { name: 'סוכר', amount: 'כוס', cost: 1 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'שמן', amount: 'כוס', cost: 3 },
      { name: 'חלב', amount: 'כוס', cost: 2 },
      { name: 'צבע מאכל אדום', amount: 'כפית', cost: 2.5 },
      { name: 'גבינת שמנת', amount: '400 גרם', cost: 8 },
      { name: 'חמאה', amount: '100 גרם', cost: 3 },
      { name: 'אבקת סוכר', amount: 'כוס', cost: 3 },
    ],
    steps: [
      'מחממים תנור ל-175°',
      'מערבבים חומרים יבשים',
      'מערבבים רטובים עם צבע',
      'משלבים ומחלקים ל-2 תבניות',
      'אופים 30 דקות',
      'מכינים קרם עם גבינה וחמאה',
      'מצפים ומקשטים',
      'עוגה מרהיבה! ❤️',
    ],
  },
  {
    id: 'lemon-cake',
    name: 'עוגת לימון',
    category: 'desserts',
    difficulty: 2,
    prepTime: 15,
    cookTime: 40,
    homeCost: 15,
    deliveryCost: 52,
    emoji: '🍋',
    image: '',
    ingredients: [
      { name: 'קמח', amount: '2 כוסות', cost: 2 },
      { name: 'סוכר', amount: 'כוס', cost: 1 },
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'שמן', amount: '½ כוס', cost: 2 },
      { name: 'מיץ לימון', amount: '½ כוס', cost: 2 },
      { name: 'גרידת לימון', amount: '2 לימונים', cost: 2 },
      { name: 'אבקת סוכר לגלייז', amount: 'כוס', cost: 3 },
    ],
    steps: [
      'מחממים תנור ל-180°',
      'מערבבים ביצים וסוכר',
      'מוסיפים שמן ומיץ לימון',
      'מוסיפים קמח וגרידה',
      'שופכים לתבנית',
      'אופים 40 דקות',
      'מכינים גלייז לימון',
      'שופכים על העוגה! 🍋',
    ],
  },
  {
    id: 'brownie-cake',
    name: 'עוגת בראוניז',
    category: 'desserts',
    difficulty: 2,
    prepTime: 15,
    cookTime: 25,
    homeCost: 18,
    deliveryCost: 60,
    emoji: '🍫',
    image: '',
    ingredients: [
      { name: 'שוקולד מריר', amount: '200 גרם', cost: 8 },
      { name: 'חמאה', amount: '100 גרם', cost: 3 },
      { name: 'סוכר', amount: '¾ כוס', cost: 1 },
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'קמח', amount: '½ כוס', cost: 1 },
      { name: 'שוקולד צ\'יפס', amount: '½ כוס', cost: 2 },
    ],
    steps: [
      'מחממים תנור ל-180°',
      'ממיסים שוקולד וחמאה',
      'מוסיפים סוכר ומערבבים',
      'מוסיפים ביצים אחת אחת',
      'מקפלים קמח וצ\'יפס',
      'שופכים לתבנית',
      'אופים 25 דקות',
      'רטוב בפנים! 🍫',
    ],
  },
  {
    id: 'banana-bread',
    name: 'עוגת בננה',
    category: 'desserts',
    difficulty: 1,
    prepTime: 15,
    cookTime: 55,
    homeCost: 12,
    deliveryCost: 48,
    emoji: '🍌',
    image: '',
    ingredients: [
      { name: 'בננות בשלות', amount: '3', cost: 3 },
      { name: 'קמח', amount: '1½ כוסות', cost: 1.5 },
      { name: 'סוכר', amount: '½ כוס', cost: 0.5 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'חמאה', amount: '80 גרם', cost: 2.5 },
      { name: 'אבקת אפייה', amount: 'כפית', cost: 0.5 },
      { name: 'אגוזי מלך', amount: '¼ כוס', cost: 2 },
    ],
    steps: [
      'מחממים תנור ל-175°',
      'מועכים בננות במזלג',
      'ממיסים חמאה ומערבבים עם בננות',
      'מוסיפים ביצים וסוכר',
      'מוסיפים קמח ואבקה',
      'מקפלים אגוזים',
      'אופים 55 דקות',
      'ריחנית ונפלאה! 🍌',
    ],
  },
  {
    id: 'pound-cake',
    name: 'עוגת חמאה',
    category: 'desserts',
    difficulty: 2,
    prepTime: 20,
    cookTime: 50,
    homeCost: 16,
    deliveryCost: 55,
    emoji: '🧈',
    image: '',
    ingredients: [
      { name: 'חמאה', amount: '200 גרם', cost: 6 },
      { name: 'סוכר', amount: 'כוס', cost: 1 },
      { name: 'ביצים', amount: '4', cost: 4 },
      { name: 'קמח', amount: '2 כוסות', cost: 2 },
      { name: 'וניל', amount: 'כפית', cost: 1 },
      { name: 'אבקת אפייה', amount: 'כפית', cost: 0.5 },
      { name: 'אבקת סוכר', amount: 'לפיזור', cost: 1.5 },
    ],
    steps: [
      'מחממים תנור ל-175°',
      'מקציפים חמאה עם סוכר',
      'מוסיפים ביצים אחת אחת',
      'מוסיפים וניל',
      'מקפלים קמח ואבקה',
      'שופכים לתבנית',
      'אופים 50 דקות',
      'מפזרים אבקת סוכר! 🧈',
    ],
  },
  {
    id: 'coffee-cake',
    name: 'עוגת קפה',
    category: 'desserts',
    difficulty: 2,
    prepTime: 20,
    cookTime: 40,
    homeCost: 17,
    deliveryCost: 58,
    emoji: '☕',
    image: '',
    ingredients: [
      { name: 'קמח', amount: '2 כוסות', cost: 2 },
      { name: 'סוכר', amount: '¾ כוס', cost: 1 },
      { name: 'קפה נמס', amount: '2 כפות', cost: 2 },
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'שמנת חמוצה', amount: '200 מ"ל', cost: 4 },
      { name: 'חמאה', amount: '100 גרם', cost: 3 },
      { name: 'שוקולד לקישוט', amount: '50 גרם', cost: 2 },
    ],
    steps: [
      'מחממים תנור ל-175°',
      'ממיסים קפה במים חמים',
      'מקציפים חמאה וסוכר',
      'מוסיפים ביצים וקפה',
      'מקפלים קמח ושמנת',
      'אופים 40 דקות',
      'ממיסים שוקולד לקישוט',
      'עוגה מבוגרים! ☕',
    ],
  },
  // ===== COOKIES (5) =====
  {
    id: 'chocolate-chip-cookies',
    name: 'עוגיות שוקולד צ\'יפס',
    category: 'desserts',
    difficulty: 1,
    prepTime: 15,
    cookTime: 12,
    homeCost: 12,
    deliveryCost: 42,
    emoji: '🍪',
    image: '',
    ingredients: [
      { name: 'חמאה', amount: '150 גרם', cost: 4.5 },
      { name: 'סוכר חום', amount: '¾ כוס', cost: 1.5 },
      { name: 'ביצה', amount: '1', cost: 1 },
      { name: 'קמח', amount: '1¾ כוסות', cost: 1.5 },
      { name: 'שוקולד צ\'יפס', amount: 'כוס', cost: 3.5 },
    ],
    steps: [
      'מחממים תנור ל-180°',
      'מערבבים חמאה וסוכר',
      'מוסיפים ביצה',
      'מוסיפים קמח ומערבבים',
      'מקפלים שוקולד צ\'יפס',
      'יוצרים כדורים על תבנית',
      'אופים 12 דקות',
      'עוגיות רכות! 🍪',
    ],
  },
  {
    id: 'oatmeal-cookies',
    name: 'עוגיות שיבולת שועל',
    category: 'desserts',
    difficulty: 1,
    prepTime: 15,
    cookTime: 15,
    homeCost: 10,
    deliveryCost: 38,
    emoji: '🌾',
    image: '',
    ingredients: [
      { name: 'שיבולת שועל', amount: '1½ כוסות', cost: 2 },
      { name: 'חמאה', amount: '100 גרם', cost: 3 },
      { name: 'סוכר חום', amount: '½ כוס', cost: 1 },
      { name: 'ביצה', amount: '1', cost: 1 },
      { name: 'קמח', amount: '¾ כוס', cost: 1 },
      { name: 'צימוקים', amount: '¼ כוס', cost: 1.5 },
      { name: 'קינמון', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'מחממים תנור ל-175°',
      'מקציפים חמאה וסוכר',
      'מוסיפים ביצה',
      'מערבבים שיבולת, קמח וקינמון',
      'מקפלים צימוקים',
      'יוצרים עוגיות שטוחות',
      'אופים 15 דקות',
      'בריאות וטעימות! 🌾',
    ],
  },
  {
    id: 'butter-cookies',
    name: 'עוגיות חמאה',
    category: 'desserts',
    difficulty: 1,
    prepTime: 20,
    cookTime: 10,
    homeCost: 9,
    deliveryCost: 35,
    emoji: '🧈',
    image: '',
    ingredients: [
      { name: 'חמאה', amount: '200 גרם', cost: 6 },
      { name: 'אבקת סוכר', amount: '½ כוס', cost: 1 },
      { name: 'קמח', amount: '2 כוסות', cost: 2 },
    ],
    steps: [
      'מקציפים חמאה רכה',
      'מוסיפים אבקת סוכר',
      'מוסיפים קמח בהדרגה',
      'מקררים 30 דקות',
      'מעצבים צורות',
      'אופים ב-175° כ-10 דקות',
      'נמסות בפה! 🧈',
    ],
  },
  {
    id: 'peanut-butter-cookies',
    name: 'עוגיות חמאת בוטנים',
    category: 'desserts',
    difficulty: 1,
    prepTime: 10,
    cookTime: 12,
    homeCost: 11,
    deliveryCost: 40,
    emoji: '🥜',
    image: '',
    ingredients: [
      { name: 'חמאת בוטנים', amount: 'כוס', cost: 6 },
      { name: 'סוכר', amount: '½ כוס', cost: 0.5 },
      { name: 'ביצה', amount: '1', cost: 1 },
      { name: 'אבקת אפייה', amount: '½ כפית', cost: 0.3 },
      { name: 'וניל', amount: 'כפית', cost: 0.5 },
      { name: 'קמח', amount: '¼ כוס', cost: 0.5 },
      { name: 'מלח', amount: 'קמצוץ', cost: 0.1 },
    ],
    steps: [
      'מחממים תנור ל-175°',
      'מערבבים הכל יחד',
      'יוצרים כדורים',
      'לוחצים עם מזלג',
      'אופים 12 דקות',
      'מצננים על התבנית',
      'עוגיות מושלמות! 🥜',
    ],
  },
  {
    id: 'tahini-cookies',
    name: 'עוגיות טחינה',
    category: 'desserts',
    difficulty: 1,
    prepTime: 10,
    cookTime: 12,
    homeCost: 10,
    deliveryCost: 38,
    emoji: '🥮',
    image: '',
    ingredients: [
      { name: 'טחינה גולמית', amount: 'כוס', cost: 5 },
      { name: 'סוכר', amount: '½ כוס', cost: 0.5 },
      { name: 'ביצה', amount: '1', cost: 1 },
      { name: 'אבקת אפייה', amount: '½ כפית', cost: 0.3 },
      { name: 'שומשום', amount: '2 כפות', cost: 1 },
      { name: 'מלח', amount: 'קמצוץ', cost: 0.1 },
    ],
    steps: [
      'מחממים תנור ל-175°',
      'מערבבים טחינה וסוכר',
      'מוסיפים ביצה ואבקה',
      'יוצרים כדורים',
      'מגלגלים בשומשום',
      'אופים 12 דקות',
      'ישראליות אותנטיות! 🥮',
    ],
  },
  // ===== TRENDY DESSERTS (10) =====
  {
    id: 'tiramisu',
    name: 'טירמיסו',
    category: 'desserts',
    difficulty: 2,
    prepTime: 30,
    cookTime: 0,
    homeCost: 25,
    deliveryCost: 78,
    emoji: '🇮🇹',
    image: '',
    ingredients: [
      { name: 'מסקרפונה', amount: '500 גרם', cost: 12 },
      { name: 'ביצים', amount: '4', cost: 4 },
      { name: 'סוכר', amount: '½ כוס', cost: 0.5 },
      { name: 'קפה אספרסו', amount: '2 כוסות', cost: 3 },
      { name: 'ביסקוויטים', amount: 'חבילה', cost: 3 },
      { name: 'קקאו לפיזור', amount: '2 כפות', cost: 1.5 },
      { name: 'ליקר אמרטו (אופציונלי)', amount: 'כף', cost: 1 },
    ],
    steps: [
      'מכינים קפה ומצננים',
      'מפרידים ביצים',
      'מקציפים חלמונים עם סוכר',
      'מוסיפים מסקרפונה',
      'מקציפים חלבונים ומקפלים',
      'טובלים ביסקוויטים בקפה',
      'מסדרים שכבות לסירוגין',
      'מקררים 4 שעות ומפזרים קקאו! 🇮🇹',
    ],
  },
  {
    id: 'creme-brulee',
    name: 'קרם ברולה',
    category: 'desserts',
    difficulty: 3,
    prepTime: 20,
    cookTime: 45,
    homeCost: 18,
    deliveryCost: 65,
    emoji: '🔥',
    image: '',
    ingredients: [
      { name: 'שמנת מתוקה', amount: '2 כוסות', cost: 8 },
      { name: 'חלמונים', amount: '5', cost: 4 },
      { name: 'סוכר', amount: '½ כוס', cost: 0.5 },
      { name: 'וניל', amount: 'מקל', cost: 3 },
      { name: 'סוכר לקרמול', amount: '3 כפות', cost: 0.5 },
    ],
    steps: [
      'מחממים שמנת עם וניל',
      'מקציפים חלמונים וסוכר',
      'מוזגים שמנת חמה לאט',
      'שופכים לרמקינים',
      'אופים במאיין 45 דקות',
      'מקררים כמה שעות',
      'מפזרים סוכר ושורפים',
      'קראנץ\' מושלם! 🔥',
    ],
  },
  {
    id: 'panna-cotta',
    name: 'פנה קוטה',
    category: 'desserts',
    difficulty: 2,
    prepTime: 15,
    cookTime: 5,
    homeCost: 14,
    deliveryCost: 52,
    emoji: '🍮',
    image: '',
    ingredients: [
      { name: 'שמנת מתוקה', amount: '2 כוסות', cost: 8 },
      { name: 'סוכר', amount: '¼ כוס', cost: 0.3 },
      { name: 'ג\'לטין', amount: 'כפית', cost: 2 },
      { name: 'וניל', amount: 'כפית', cost: 1 },
      { name: 'פירות יער', amount: 'כוס', cost: 2.7 },
    ],
    steps: [
      'משרים ג\'לטין במים',
      'מחממים שמנת וסוכר',
      'מוסיפים ג\'לטין ומערבבים',
      'מוסיפים וניל',
      'שופכים לכוסות',
      'מקררים 4 שעות',
      'מגישים עם פירות יער! 🍮',
    ],
  },
  {
    id: 'mochi',
    name: 'מוצ\'י',
    category: 'desserts',
    difficulty: 3,
    prepTime: 30,
    cookTime: 3,
    homeCost: 15,
    deliveryCost: 55,
    emoji: '🍡',
    image: '',
    ingredients: [
      { name: 'קמח אורז', amount: 'כוס', cost: 4 },
      { name: 'סוכר', amount: '¼ כוס', cost: 0.3 },
      { name: 'מים', amount: '¾ כוס', cost: 0 },
      { name: 'עמילן תירס', amount: 'לפיזור', cost: 0.5 },
      { name: 'גלידה או שעועית אדומה', amount: 'למילוי', cost: 5 },
      { name: 'צבע מאכל (אופציונלי)', amount: 'טיפות', cost: 0.5 },
    ],
    steps: [
      'מערבבים קמח, סוכר ומים',
      'מחממים במיקרו 3 דקות',
      'מערבבים כל דקה',
      'מפזרים עמילן על משטח',
      'מורחים את הבצק',
      'חותכים עיגולים',
      'ממלאים וסוגרים',
      'קינוח יפני טרנדי! 🍡',
    ],
  },
  {
    id: 'churros',
    name: 'צ\'ורוס',
    category: 'desserts',
    difficulty: 2,
    prepTime: 20,
    cookTime: 15,
    homeCost: 12,
    deliveryCost: 45,
    emoji: '🥖',
    image: '',
    ingredients: [
      { name: 'מים', amount: 'כוס', cost: 0 },
      { name: 'חמאה', amount: '50 גרם', cost: 1.5 },
      { name: 'סוכר', amount: 'כף', cost: 0.2 },
      { name: 'קמח', amount: 'כוס', cost: 1 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'שמן לטיגון', amount: 'לטיגון עמוק', cost: 3 },
      { name: 'סוכר וקינמון', amount: 'לציפוי', cost: 0.5 },
      { name: 'שוקולד לטבילה', amount: '100 גרם', cost: 3.8 },
    ],
    steps: [
      'מרתיחים מים עם חמאה וסוכר',
      'מוסיפים קמח ומערבבים חזק',
      'מצננים ומוסיפים ביצים',
      'מכניסים לשקית זירוז',
      'מטגנים בשמן חם',
      'מגלגלים בסוכר וקינמון',
      'ממיסים שוקולד לטבילה',
      'ספרדי אותנטי! 🥖',
    ],
  },
  {
    id: 'macarons',
    name: 'מקרונים',
    category: 'desserts',
    difficulty: 4,
    prepTime: 45,
    cookTime: 15,
    homeCost: 22,
    deliveryCost: 85,
    emoji: '🌈',
    image: '',
    ingredients: [
      { name: 'קמח שקדים', amount: '100 גרם', cost: 8 },
      { name: 'אבקת סוכר', amount: '100 גרם', cost: 1.5 },
      { name: 'חלבוני ביצה', amount: '3', cost: 2 },
      { name: 'סוכר', amount: '¼ כוס', cost: 0.3 },
      { name: 'צבעי מאכל', amount: 'לבחירה', cost: 2 },
      { name: 'גנאש/קרם למילוי', amount: '150 גרם', cost: 5 },
    ],
    steps: [
      'מנפים קמח שקדים ואבקת סוכר',
      'מקציפים חלבונים עם סוכר למרנג',
      'מקפלים ב-macaronage',
      'מכניסים לשקית זירוז',
      'יוצרים עיגולים על תבנית',
      'משאירים 30 דק\' עד שמתייבש',
      'אופים ב-150° כ-15 דקות',
      'ממלאים וממתינים יום! 🌈',
    ],
  },
  {
    id: 'basque-cheesecake',
    name: 'צ\'יזקייק באסקי',
    category: 'desserts',
    difficulty: 2,
    prepTime: 15,
    cookTime: 45,
    homeCost: 22,
    deliveryCost: 72,
    emoji: '🔥',
    image: '',
    ingredients: [
      { name: 'גבינת שמנת', amount: '600 גרם', cost: 12 },
      { name: 'סוכר', amount: 'כוס', cost: 1 },
      { name: 'ביצים', amount: '5', cost: 5 },
      { name: 'שמנת מתוקה', amount: 'כוס', cost: 4 },
    ],
    steps: [
      'מחממים תנור ל-220°',
      'מרפדים תבנית בנייר אפייה',
      'מערבבים גבינה וסוכר',
      'מוסיפים ביצים אחת אחת',
      'מוסיפים שמנת',
      'שופכים לתבנית',
      'אופים 45 דקות עד שחרוך',
      'הטרנד הכי חם! 🔥',
    ],
  },
  {
    id: 'affogato',
    name: 'אפוגטו',
    category: 'desserts',
    difficulty: 1,
    prepTime: 3,
    cookTime: 0,
    homeCost: 10,
    deliveryCost: 38,
    emoji: '☕',
    image: '',
    ingredients: [
      { name: 'גלידת וניל', amount: '2 כדורים', cost: 5 },
      { name: 'אספרסו חם', amount: 'שוט', cost: 3 },
      { name: 'ביסקוטי (אופציונלי)', amount: '1', cost: 2 },
    ],
    steps: [
      'מניחים גלידה בכוס',
      'מכינים אספרסו חזק',
      'שופכים מיד על הגלידה',
      'מגישים עם ביסקוטי',
      'פשוט ומושלם! ☕',
    ],
  },
  {
    id: 'matcha-lava-cake',
    name: 'עוגת לבה מאצ\'ה',
    category: 'desserts',
    difficulty: 3,
    prepTime: 15,
    cookTime: 12,
    homeCost: 20,
    deliveryCost: 68,
    emoji: '🍵',
    image: '',
    ingredients: [
      { name: 'שוקולד לבן', amount: '100 גרם', cost: 5 },
      { name: 'חמאה', amount: '60 גרם', cost: 2 },
      { name: 'אבקת מאצ\'ה', amount: '2 כפות', cost: 6 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'סוכר', amount: '3 כפות', cost: 0.3 },
      { name: 'קמח', amount: '2 כפות', cost: 0.3 },
    ],
    steps: [
      'מחממים תנור ל-200°',
      'ממיסים שוקולד לבן עם חמאה',
      'מוסיפים מאצ\'ה ומערבבים',
      'מקציפים ביצים וסוכר',
      'משלבים התערובות',
      'מוסיפים קמח',
      'אופים 12 דקות',
      'לבה ירוקה זורמת! 🍵',
    ],
  },
  {
    id: 'dubai-chocolate',
    name: 'שוקולד דובאי',
    category: 'desserts',
    difficulty: 2,
    prepTime: 30,
    cookTime: 0,
    homeCost: 25,
    deliveryCost: 95,
    emoji: '🍫',
    image: '',
    ingredients: [
      { name: 'שוקולד חלב', amount: '200 גרם', cost: 8 },
      { name: 'פסטה פיסטוק', amount: '100 גרם', cost: 10 },
      { name: 'כדאיף', amount: '50 גרם', cost: 3 },
      { name: 'חמאה', amount: '30 גרם', cost: 1 },
      { name: 'טחינה', amount: '2 כפות', cost: 2 },
      { name: 'מלח ים', amount: 'קמצוץ', cost: 0.2 },
    ],
    steps: [
      'מטגנים כדאיף בחמאה עד פריך',
      'מערבבים פסטה פיסטוק עם כדאיף',
      'מוסיפים טחינה',
      'ממיסים שוקולד',
      'יוצרים תבניות שוקולד',
      'ממלאים בתערובת פיסטוק',
      'סוגרים עם שוקולד',
      'הטרנד הויראלי! 🍫',
    ],
  },
];

export const getRecipeById = (id: string): Recipe | undefined => {
  return recipes.find(r => r.id === id);
};

export const getRecipesByCategory = (category: RecipeCategory): Recipe[] => {
  return recipes.filter(r => r.category === category);
};

export const calculateSavings = (recipe: Recipe): number => {
  return recipe.deliveryCost - recipe.homeCost;
};

export const categoryLabels: Record<RecipeCategory, string> = {
  easy: 'קל',
  beginner: 'למתחילים',
  cheap: 'חסכוני',
  fast: 'מהיר',
  protein: 'חלבון',
  vegetarian: 'צמחוני',
  kosher: 'כשר',
  desserts: 'קינוחים',
  meat: 'בשר',
};

export const categoryEmojis: Record<RecipeCategory, string> = {
  easy: '🍳',
  beginner: '👶',
  cheap: '💸',
  fast: '⏱️',
  protein: '💪',
  vegetarian: '🌱',
  kosher: '✡️',
  desserts: '🍰',
  meat: '🥩',
};