import { Recipe, RecipeCategory } from './types';

export const recipes: Recipe[] = [
  {
    id: 'hamburger',
    name: 'המבורגר ביתי',
    category: 'easy',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    homeCost: 12,
    deliveryCost: 65,
    emoji: '🍔',
    image: '',
    ingredients: [
      { name: 'בשר טחון', amount: '150 גרם', cost: 6 },
      { name: 'לחמנייה', amount: '1', cost: 2 },
      { name: 'עגבנייה', amount: '½', cost: 1 },
      { name: 'חסה', amount: 'עלים', cost: 1 },
      { name: 'בצל', amount: 'פרוסה', cost: 0.5 },
      { name: 'גבינה צהובה', amount: 'פרוסה', cost: 1.5 },
    ],
    steps: [
      'מוציאים את הבשר מהמקרר 15 דקות לפני הבישול',
      'מגלגלים כדור בשר ולוחצים לקציצה שטוחה',
      'מתבלים במלח ופלפל משני הצדדים',
      'מחממים מחבת על אש גבוהה',
      'מניחים את הקציצה ולא נוגעים! 3 דקות',
      'הופכים ומניחים גבינה מעל',
      'עוד 3 דקות עד שהגבינה נמסה',
      'מרכיבים על הלחמנייה עם הירקות',
      'בתיאבון! 🎉',
    ],
  },
  {
    id: 'pasta-tomato',
    name: 'פסטה ברוטב עגבניות',
    category: 'beginner',
    difficulty: 1,
    prepTime: 5,
    cookTime: 20,
    homeCost: 8,
    deliveryCost: 55,
    emoji: '🍝',
    image: '',
    ingredients: [
      { name: 'פסטה', amount: '100 גרם', cost: 2 },
      { name: 'רסק עגבניות', amount: '½ קופסה', cost: 3 },
      { name: 'שום', amount: '2 שיניים', cost: 0.5 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'בזיליקום', amount: 'קמצוץ', cost: 0.5 },
      { name: 'פרמזן', amount: 'כף', cost: 1 },
    ],
    steps: [
      'מחממים סיר גדול עם מים ומוסיפים מלח',
      'כשהמים רותחים, מוסיפים את הפסטה',
      'מבשלים לפי ההוראות על האריזה',
      'במחבת נפרדת - מחממים שמן זית',
      'מוסיפים שום קצוץ ומטגנים דקה',
      'מוסיפים רסק עגבניות ובזיליקום',
      'מבשלים 5 דקות על אש נמוכה',
      'מסננים את הפסטה ומוסיפים לרוטב',
      'מפזרים פרמזן ומגישים! 🍝',
    ],
  },
  {
    id: 'shakshuka',
    name: 'שקשוקה',
    category: 'cheap',
    difficulty: 2,
    prepTime: 5,
    cookTime: 15,
    homeCost: 10,
    deliveryCost: 45,
    emoji: '🍳',
    image: '',
    ingredients: [
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'עגבניות מרוסקות', amount: 'קופסה', cost: 4 },
      { name: 'בצל', amount: '½', cost: 0.5 },
      { name: 'פלפל', amount: '½', cost: 1 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
      { name: 'כמון', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'מחממים שמן במחבת עמוקה',
      'מטגנים בצל חתוך עד שמזהיב',
      'מוסיפים פלפל חתוך וממשיכים 3 דקות',
      'מוסיפים עגבניות, פפריקה וכמון',
      'מבשלים 5 דקות עד שמתעבה קצת',
      'עושים גומות ברוטב',
      'שוברים ביצה לכל גומה',
      'מכסים ומבשלים 5 דקות',
      'מגישים עם לחם! 🥖',
    ],
  },
  {
    id: 'omelette',
    name: 'חביתה עשירה',
    category: 'fast',
    difficulty: 1,
    prepTime: 3,
    cookTime: 5,
    homeCost: 6,
    deliveryCost: 35,
    emoji: '🥚',
    image: '',
    ingredients: [
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'גבינה צהובה', amount: 'פרוסות', cost: 2 },
      { name: 'חלב', amount: 'כף', cost: 0.3 },
      { name: 'מלח ופלפל', amount: 'קמצוץ', cost: 0.2 },
    ],
    steps: [
      'טורפים ביצים עם חלב, מלח ופלפל',
      'מחממים מחבת עם חמאה או שמן',
      'שופכים את התערובת למחבת',
      'כשמתחיל להיקפא - מוסיפים גבינה',
      'מקפלים לחצי ומגישים! 🍳',
    ],
  },
  {
    id: 'rice-chicken',
    name: 'עוף ואורז',
    category: 'protein',
    difficulty: 2,
    prepTime: 10,
    cookTime: 30,
    homeCost: 18,
    deliveryCost: 70,
    emoji: '🍗',
    image: '',
    ingredients: [
      { name: 'חזה עוף', amount: '200 גרם', cost: 10 },
      { name: 'אורז', amount: 'כוס', cost: 2 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
      { name: 'שום', amount: 'שן', cost: 0.5 },
      { name: 'לימון', amount: '½', cost: 1 },
    ],
    steps: [
      'מבשלים אורז לפי ההוראות',
      'חותכים עוף לרצועות',
      'מתבלים בפפריקה, מלח ופלפל',
      'מחממים שמן במחבת',
      'מטגנים עוף 5-6 דקות מכל צד',
      'מוסיפים שום ומטגנים דקה',
      'סוחטים לימון מעל',
      'מגישים על האורז! 🍚',
    ],
  },
  {
    id: 'toast-cheese',
    name: 'טוסט גבינה מושלם',
    category: 'fast',
    difficulty: 1,
    prepTime: 2,
    cookTime: 5,
    homeCost: 5,
    deliveryCost: 28,
    emoji: '🧀',
    image: '',
    ingredients: [
      { name: 'לחם', amount: '2 פרוסות', cost: 1.5 },
      { name: 'גבינה צהובה', amount: 'פרוסות', cost: 2.5 },
      { name: 'חמאה', amount: 'כף', cost: 1 },
    ],
    steps: [
      'מורחים חמאה על הלחם מבחוץ',
      'מניחים גבינה בין הפרוסות',
      'מחממים מחבת על אש בינונית',
      'מטגנים עד שהלחם מוזהב',
      'הופכים ומטגנים מהצד השני',
      'מגישים חם! 🧀',
    ],
  },
  {
    id: 'tortilla',
    name: 'טורטייה ביתית',
    category: 'easy',
    difficulty: 2,
    prepTime: 10,
    cookTime: 10,
    homeCost: 14,
    deliveryCost: 52,
    emoji: '🌮',
    image: '',
    ingredients: [
      { name: 'טורטייה', amount: '2', cost: 3 },
      { name: 'עוף שניצל', amount: '150 גרם', cost: 7 },
      { name: 'חסה', amount: 'עלים', cost: 1 },
      { name: 'עגבנייה', amount: '1', cost: 1 },
      { name: 'רוטב טחינה', amount: 'כף', cost: 1 },
      { name: 'מלפפון חמוץ', amount: '2', cost: 1 },
    ],
    steps: [
      'מטגנים שניצל עוף במחבת עד שמוזהב',
      'חותכים את השניצל לרצועות',
      'חותכים ירקות לרצועות דקות',
      'מחממים טורטייה במחבת יבשה',
      'מניחים עוף במרכז הטורטייה',
      'מוסיפים ירקות ורוטב',
      'מגלגלים ומגישים! 🌮',
    ],
  },
  {
    id: 'fried-rice',
    name: 'אורז מוקפץ',
    category: 'cheap',
    difficulty: 2,
    prepTime: 5,
    cookTime: 15,
    homeCost: 9,
    deliveryCost: 48,
    emoji: '🍚',
    image: '',
    ingredients: [
      { name: 'אורז מבושל', amount: '2 כוסות', cost: 3 },
      { name: 'ביצים', amount: '2', cost: 2 },
      { name: 'בצל ירוק', amount: '2', cost: 1 },
      { name: 'שמן שומשום', amount: 'כפית', cost: 1 },
      { name: 'סויה', amount: 'כף', cost: 1 },
      { name: 'ירקות קפואים', amount: 'חופן', cost: 1 },
    ],
    steps: [
      'מחממים מחבת או ווק על אש גבוהה',
      'מוסיפים שמן ומקפיצים ירקות 2 דק׳',
      'דוחפים לצד ומטגנים ביצים מקושקשות',
      'מוסיפים אורז קר ומערבבים',
      'מוסיפים סויה ושמן שומשום',
      'מקפיצים 3 דקות על אש גבוהה',
      'מפזרים בצל ירוק ומגישים! 🥢',
    ],
  },
  {
    id: 'protein-salad',
    name: 'סלט חלבון',
    category: 'protein',
    difficulty: 1,
    prepTime: 10,
    cookTime: 0,
    homeCost: 15,
    deliveryCost: 58,
    emoji: '🥗',
    image: '',
    ingredients: [
      { name: 'חזה עוף מבושל', amount: '150 גרם', cost: 8 },
      { name: 'עלי חסה', amount: 'קערה', cost: 2 },
      { name: 'עגבניות שרי', amount: '10', cost: 2 },
      { name: 'ביצה קשה', amount: '1', cost: 1 },
      { name: 'גבינה בולגרית', amount: '50 גרם', cost: 2 },
    ],
    steps: [
      'קורעים עלי חסה לקערה',
      'חותכים עגבניות שרי לחצי',
      'חותכים עוף לקוביות',
      'מפוררים גבינה בולגרית',
      'חותכים ביצה קשה לרבעים',
      'מערבבים הכל יחד',
      'מוסיפים רוטב לבחירה! 🥗',
    ],
  },
  {
    id: 'pan-pizza',
    name: 'פיצה במחבת',
    category: 'beginner',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    homeCost: 11,
    deliveryCost: 55,
    emoji: '🍕',
    image: '',
    ingredients: [
      { name: 'בצק פיצה', amount: 'חבילה', cost: 4 },
      { name: 'רוטב עגבניות', amount: '3 כפות', cost: 2 },
      { name: 'מוצרלה', amount: '100 גרם', cost: 4 },
      { name: 'זיתים', amount: 'קומץ', cost: 0.5 },
      { name: 'אורגנו', amount: 'קמצוץ', cost: 0.5 },
    ],
    steps: [
      'מורחים בצק על מחבת משומנת',
      'מחממים על אש בינונית',
      'מורחים רוטב עגבניות',
      'מפזרים גבינה מוצרלה',
      'מוסיפים זיתים ואורגנו',
      'מכסים ומבשלים 10 דקות',
      'הגבינה נמסה? מוכן! 🍕',
    ],
  },
  {
    id: 'toast-avocado',
    name: 'טוסט אבוקדו',
    category: 'fast',
    difficulty: 1,
    prepTime: 5,
    cookTime: 3,
    homeCost: 8,
    deliveryCost: 42,
    emoji: '🥑',
    image: '',
    ingredients: [
      { name: 'לחם מחמצת', amount: '2 פרוסות', cost: 3 },
      { name: 'אבוקדו בשל', amount: '½', cost: 3 },
      { name: 'לימון', amount: 'סחיטה', cost: 0.5 },
      { name: 'מלח ופלפל', amount: 'קמצוץ', cost: 0.2 },
      { name: 'שומשום', amount: 'קמצוץ', cost: 0.3 },
    ],
    steps: [
      'קולים לחם בטוסטר',
      'מועכים אבוקדו במזלג',
      'מוסיפים לימון, מלח ופלפל',
      'מורחים על הלחם הקלוי',
      'מפזרים שומשום',
      'מגישים מיד! 🥑',
    ],
  },
  {
    id: 'noodles',
    name: 'נודלס פשוט',
    category: 'fast',
    difficulty: 1,
    prepTime: 3,
    cookTime: 10,
    homeCost: 7,
    deliveryCost: 38,
    emoji: '🍜',
    image: '',
    ingredients: [
      { name: 'נודלס אטריות', amount: 'חבילה', cost: 3 },
      { name: 'ירקות מוקפצים', amount: 'כוס', cost: 2 },
      { name: 'סויה', amount: 'כף', cost: 0.5 },
      { name: 'שמן שומשום', amount: 'כפית', cost: 0.5 },
      { name: 'שום', amount: 'שן', cost: 0.5 },
      { name: 'בצל ירוק', amount: '1', cost: 0.5 },
    ],
    steps: [
      'מבשלים נודלס לפי ההוראות',
      'מחממים ווק עם שמן',
      'מוסיפים שום ומטגנים 30 שניות',
      'מוסיפים ירקות ומקפיצים 2 דק׳',
      'מוסיפים נודלס מסונן',
      'מוסיפים סויה ושמן שומשום',
      'מפזרים בצל ירוק ומגישים! 🍜',
    ],
  },
  {
    id: 'vegetable-stir-fry',
    name: 'ירקות מוקפצים',
    category: 'vegetarian',
    difficulty: 1,
    prepTime: 10,
    cookTime: 8,
    homeCost: 12,
    deliveryCost: 45,
    emoji: '🥦',
    image: '',
    ingredients: [
      { name: 'ברוקולי', amount: 'ראש קטן', cost: 4 },
      { name: 'גזר', amount: '1', cost: 1 },
      { name: 'פלפל צבעוני', amount: '1', cost: 2 },
      { name: 'פטריות', amount: '100 גרם', cost: 3 },
      { name: 'סויה', amount: 'כף', cost: 1 },
      { name: 'שום', amount: '2 שיניים', cost: 1 },
    ],
    steps: [
      'חותכים ירקות לחתיכות קטנות',
      'מחממים ווק על אש גבוהה',
      'מוסיפים שמן ושום',
      'מוסיפים ירקות קשים קודם (גזר)',
      'אחרי 2 דק׳ מוסיפים שאר הירקות',
      'מקפיצים 4-5 דקות',
      'מוסיפים סויה ומגישים! 🥦',
    ],
  },
  {
    id: 'hummus-plate',
    name: 'צלחת חומוס',
    category: 'vegetarian',
    difficulty: 1,
    prepTime: 5,
    cookTime: 0,
    homeCost: 10,
    deliveryCost: 38,
    emoji: '🧆',
    image: '',
    ingredients: [
      { name: 'חומוס מוכן', amount: 'קופסה', cost: 5 },
      { name: 'טחינה', amount: 'כף', cost: 2 },
      { name: 'פטרוזיליה', amount: 'קומץ', cost: 1 },
      { name: 'פפריקה', amount: 'קמצוץ', cost: 0.5 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'פיתה', amount: '1', cost: 0.5 },
    ],
    steps: [
      'שופכים חומוס לצלחת',
      'יוצרים גומה במרכז',
      'מוסיפים טחינה לגומה',
      'מפזרים פפריקה ופטרוזיליה',
      'שופכים שמן זית מעל',
      'מגישים עם פיתה חמה! 🧆',
    ],
  },
];

export const getRecipeById = (id: string): Recipe | undefined => {
  return recipes.find(r => r.id === id);
};

export const getRecipesByCategory = (category: RecipeCategory): Recipe[] => {
  return recipes.filter(r => r.category === category);
};

export const calculateSavings = (recipe: Recipe): number => {
  return recipe.deliveryCost - recipe.homeCost;
};

export const categoryLabels: Record<RecipeCategory, string> = {
  easy: 'קל',
  beginner: 'למתחילים',
  cheap: 'חסכוני',
  fast: 'מהיר',
  protein: 'חלבון',
  vegetarian: 'צמחוני',
};

export const categoryEmojis: Record<RecipeCategory, string> = {
  easy: '🍳',
  beginner: '👶',
  cheap: '💸',
  fast: '⏱️',
  protein: '🥩',
  vegetarian: '🌱',
};