import { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: 'hamburger',
    name: 'המבורגר ביתי',
    category: 'easy',
    difficulty: 2,
    prepTime: 10,
    cookTime: 15,
    homeCost: 12,
    deliveryCost: 65,
    emoji: '🍔',
    image: '',
    ingredients: [
      { name: 'בשר טחון', amount: '150 גרם', cost: 6 },
      { name: 'לחמנייה', amount: '1', cost: 2 },
      { name: 'עגבנייה', amount: '½', cost: 1 },
      { name: 'חסה', amount: 'עלים', cost: 1 },
      { name: 'בצל', amount: 'פרוסה', cost: 0.5 },
      { name: 'גבינה צהובה', amount: 'פרוסה', cost: 1.5 },
    ],
    steps: [
      'מוציאים את הבשר מהמקרר 15 דקות לפני הבישול',
      'מגלגלים כדור בשר ולוחצים לקציצה שטוחה',
      'מתבלים במלח ופלפל משני הצדדים',
      'מחממים מחבת על אש גבוהה',
      'מניחים את הקציצה ולא נוגעים! 3 דקות',
      'הופכים ומניחים גבינה מעל',
      'עוד 3 דקות עד שהגבינה נמסה',
      'מרכיבים על הלחמנייה עם הירקות',
      'בתיאבון! 🎉',
    ],
  },
  {
    id: 'pasta-tomato',
    name: 'פסטה ברוטב עגבניות',
    category: 'beginner',
    difficulty: 1,
    prepTime: 5,
    cookTime: 20,
    homeCost: 8,
    deliveryCost: 55,
    emoji: '🍝',
    image: '',
    ingredients: [
      { name: 'פסטה', amount: '100 גרם', cost: 2 },
      { name: 'רסק עגבניות', amount: '½ קופסה', cost: 3 },
      { name: 'שום', amount: '2 שיניים', cost: 0.5 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'בזיליקום', amount: 'קמצוץ', cost: 0.5 },
      { name: 'פרמזן', amount: 'כף', cost: 1 },
    ],
    steps: [
      'מחממים סיר גדול עם מים ומוסיפים מלח',
      'כשהמים רותחים, מוסיפים את הפסטה',
      'מבשלים לפי ההוראות על האריזה',
      'במחבת נפרדת - מחממים שמן זית',
      'מוסיפים שום קצוץ ומטגנים דקה',
      'מוסיפים רסק עגבניות ובזיליקום',
      'מבשלים 5 דקות על אש נמוכה',
      'מסננים את הפסטה ומוסיפים לרוטב',
      'מפזרים פרמזן ומגישים! 🍝',
    ],
  },
  {
    id: 'shakshuka',
    name: 'שקשוקה',
    category: 'cheap',
    difficulty: 2,
    prepTime: 5,
    cookTime: 15,
    homeCost: 10,
    deliveryCost: 45,
    emoji: '🍳',
    image: '',
    ingredients: [
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'עגבניות מרוסקות', amount: 'קופסה', cost: 4 },
      { name: 'בצל', amount: '½', cost: 0.5 },
      { name: 'פלפל', amount: '½', cost: 1 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
      { name: 'כמון', amount: 'כפית', cost: 0.5 },
    ],
    steps: [
      'מחממים שמן במחבת עמוקה',
      'מטגנים בצל חתוך עד שמזהיב',
      'מוסיפים פלפל חתוך וממשיכים 3 דקות',
      'מוסיפים עגבניות, פפריקה וכמון',
      'מבשלים 5 דקות עד שמתעבה קצת',
      'עושים גומות ברוטב',
      'שוברים ביצה לכל גומה',
      'מכסים ומבשלים 5 דקות',
      'מגישים עם לחם! 🥖',
    ],
  },
  {
    id: 'omelette',
    name: 'חביתה עשירה',
    category: 'fast',
    difficulty: 1,
    prepTime: 3,
    cookTime: 5,
    homeCost: 6,
    deliveryCost: 35,
    emoji: '🥚',
    image: '',
    ingredients: [
      { name: 'ביצים', amount: '3', cost: 3 },
      { name: 'גבינה צהובה', amount: 'פרוסות', cost: 2 },
      { name: 'חלב', amount: 'כף', cost: 0.3 },
      { name: 'מלח ופלפל', amount: 'קמצוץ', cost: 0.2 },
    ],
    steps: [
      'טורפים ביצים עם חלב, מלח ופלפל',
      'מחממים מחבת עם חמאה או שמן',
      'שופכים את התערובת למחבת',
      'כשמתחיל להיקפא - מוסיפים גבינה',
      'מקפלים לחצי ומגישים! 🍳',
    ],
  },
  {
    id: 'rice-chicken',
    name: 'עוף ואורז',
    category: 'easy',
    difficulty: 2,
    prepTime: 10,
    cookTime: 30,
    homeCost: 18,
    deliveryCost: 70,
    emoji: '🍗',
    image: '',
    ingredients: [
      { name: 'חזה עוף', amount: '200 גרם', cost: 10 },
      { name: 'אורז', amount: 'כוס', cost: 2 },
      { name: 'שמן זית', amount: 'כף', cost: 1 },
      { name: 'פפריקה', amount: 'כפית', cost: 0.5 },
      { name: 'שום', amount: 'שן', cost: 0.5 },
      { name: 'לימון', amount: '½', cost: 1 },
    ],
    steps: [
      'מבשלים אורז לפי ההוראות',
      'חותכים עוף לרצועות',
      'מתבלים בפפריקה, מלח ופלפל',
      'מחממים שמן במחבת',
      'מטגנים עוף 5-6 דקות מכל צד',
      'מוסיפים שום ומטגנים דקה',
      'סוחטים לימון מעל',
      'מגישים על האורז! 🍚',
    ],
  },
  {
    id: 'toast-cheese',
    name: 'טוסט גבינה מושלם',
    category: 'fast',
    difficulty: 1,
    prepTime: 2,
    cookTime: 5,
    homeCost: 5,
    deliveryCost: 28,
    emoji: '🧀',
    image: '',
    ingredients: [
      { name: 'לחם', amount: '2 פרוסות', cost: 1.5 },
      { name: 'גבינה צהובה', amount: 'פרוסות', cost: 2.5 },
      { name: 'חמאה', amount: 'כף', cost: 1 },
    ],
    steps: [
      'מורחים חמאה על הלחם מבחוץ',
      'מניחים גבינה בין הפרוסות',
      'מחממים מחבת על אש בינונית',
      'מטגנים עד שהלחם מוזהב',
      'הופכים ומטגנים מהצד השני',
      'מגישים חם! 🧀',
    ],
  },
];

export const getRecipeById = (id: string): Recipe | undefined => {
  return recipes.find(r => r.id === id);
};

export const getRecipesByCategory = (category: Recipe['category']): Recipe[] => {
  return recipes.filter(r => r.category === category);
};

export const calculateSavings = (recipe: Recipe): number => {
  return recipe.deliveryCost - recipe.homeCost;
};

export const categoryLabels: Record<Recipe['category'], string> = {
  easy: 'קל',
  beginner: 'למתחילים',
  cheap: 'חסכוני',
  fast: 'מהיר',
};
